// This appears under the pictures on the square, and at the top of its
// Format: Text.
// individual page.
// Format: text.
const heading =  "I'd love to be vegan, but...";


// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: text.
const alternatives = `I’m an animal lover. I was vegan/vegetarian but…`;


// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>Noble aspirations are a good thing, but our character is defined by making our actions consistent with our aspirations. You may love animals or wish there was less suffering in the world, but if you don’t believe any of these things strongly enough to do much about them, you need to question your priorities. Thoughts and prayers, virtue signalling, expressions of what a compassionate person you are, these things are not bad in themselves unless they are all you are willing to do to alleviate suffering, then they are often empty and meaningless.</p>`;


// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>Veganism has become mainstream and society more conscious of the ethical conversation around veganism. Old-school vegans remember having to explain what veganism or even vegetarianism was. I’ve personally had to spell v e g a n countless times to mystified people, but now most people are familiar with the term. That people know roughly what veganism is and so many have considered or even tried it, is a positive sign that veganism and the ideas it represents are on an upward trend.</p>


<p>This is in accord with the future most vegans believe in, that the moral arc of history will bend towards justice for animals. We assume not only that our collective ethical progress will take us beyond sending billions of animals into factory farms and slaughterhouses, but that society will be mystified that so many unquestioningly participated in such a vast atrocity. Countless eminent thinkers, including Noam Chomsky, Steven Pinker and Richard Dawkins, have said that animal rights are an obvious area for future ethical progress, even though none of them is vegan. From a vegan perspective, it is easier to forgive someone who hasn’t heard about or properly understood veganism, over someone who recognises the ethical issues but ignores them. Here is something people can do at relatively little cost to themselves, to reduce the suffering of other sentient creatures and their environmental footprint, but they decide that it doesn’t fit their lifestyle or “is not for them”. To be blunt, if our moral framework allows us to contribute to animals living in factory farms, then it is a limited and self-biassed moral framework. People may look around for support, that they are only doing what their family, friends, co-workers and most of society do, but ethics is not about conformity, indeed ethics is at its most powerful and meaningful when it requires the rejection of conformity.</p>


<p>We shouldn’t ignore the positives that this change in the societal narrative about animals represents. We should give credit to those who are willing to sincerely discuss issues about animal rights or the moral imperative of veganism. In this world of minds closed to change, of selfishness and egocentrism, here are people that might be open to a positive, mainly selfless change. An ethical vegan’s pulse might quicken a little seeing this glimmer of hope for a more compassionate world. Maybe, if we can just say the right thing we can do some powerful good for animals, the world and the person.</p>


<p>Hope is often a double-edged sword. If a person starts explaining why they can’t be vegan, most vegans will want to help the person over any hurdles. Of course, the person might be more justifying not being vegan rather than seriously considering veganism and if we misjudge the moment or our tone these conversations can come across as preachy or “salesy”. Having a detailed, conversation-ending answer for every justification you have heard a hundred times before, drowning a person in facts rather than empathy, and ignoring their unique complex emotional reality, can all be counterproductive. We need to have the conversation the person is open to, which helps them change their frame of reference, not the one we have rehearsed in our minds. We often embark upon a conversation we think might have resonated with us before we were vegan, without recognising that we all have different levels of openness to change at different contexts in our lives, we like to think we were always open to ethical challenges but it’s likely that’s not true. This last point is interesting, people asked why they became vegan will often give a very specific answer, for instance, they read a pamphlet, watched a video or were positively influenced by a person. No doubt these were pivotal moments, but there was probably a long process that lead up to people being receptive to the right information at that moment. A foundation needs to be laid in each of us, a crack in our minds opened for some light to seep in, a different world/self-made conceptually possible, before there is a chance for deeper change. We need to understand where people are; does someone even know about factory farms, or do they assume animals probably have reasonable lives in them, or do they think the way we treat animals might be wrong but don’t know what to do about it, or are they vegetarian because they instinctively think killing animals is wrong but don’t properly understand the death and suffering in the egg and dairy industries, or are they attracted to the idea of veganism but just need to know what steps to take, or something else unique to them. Chances to sincerely discuss our relationship with the non-human world are precious, we should not squander them in debate or give people information overload, we need to focus on the person in front of us and how we can help their ethical journey, even if they don’t know they are on one.</p>


<p>Communication is hard, partly because people are so unique, often so very different from us as to be almost unrelatable. Some people will judge a discussion by its rationality, they are best reached via a clear coherent argument and too much emotion will make them feel they are being manipulated. Others are more sensitive to the interpersonal aspects of a conversation, too little emotion might come off as cold, facts aren’t inconsequential but an emotional connection with them and animals is more likely to resonate. People have different life experiences, cultures, sensitivities, and levels of tolerance for difficult topics. People also have psychological defence mechanisms and many will instinctively turn away from discussions or depictions of suffering, perhaps as echoes or reminders of their own pain or trauma. People are also at different stages of knowledge about issues and varying openness to change. Some people need to know how and others why. Blundering into a system without understanding it is usually a mistake, especially in systems as complex as human minds. When someone says they can’t be vegan, we have to start by listening and learning, not focusing on convincing them but on how we might help them.</p>


<p>One place many passionate vegans can be short-sighted is in their attitude towards people who used to be vegan. “You were never really vegan” is the cliched comment made in these cases. This way of thinking ignores many realities and circumstances in people’s lives. The most obvious is that all of us sometimes need a couple of attempts at making life changes, even ones we believe in. Perhaps people were undergoing something emotionally challenging while they were trying to become vegan, and they need some healing and re-energising before they will be ready to try again. People’s motivations also vary. Not everyone becomes vegan for animal rights or from a reverence for the non-human world. Some come to it for health, or because they were in a relationship or social circle that made it easy for them to be vegan. The attrition rate of vegans, especially those who aren’t motivated by ethical considerations, is high. Sometimes our movement focuses too much on getting people to become vegan and doesn’t do enough work on helping already existing vegans to be happy, healthy and deeply informed. People have a deep need for social connection and not all social circles are as tolerant of veganism as they should be. As vegans, we need to think about how we are helping foster community that makes it easier for people to make ethical choices without negative social ramifications. Just being around a group of kind, committed vegans every now and then can help people feel less alone and different in the world.</p>


<p>With health, a lot of vegans (often new vegans) promote unrealistic claims for the vegan diet. Literally, they will say that vegans never get sick or are immune to viruses and they often don’t even advocate taking a regular B12 supplement. Not only are these positions dangerous and empirically untrue, but promoting veganism as a miracle cure can lead to disappointment and disillusionment in people who come to it with unrealistic expectations. The highest nutritional bodies in the world reaffirm that a well-planned vegan diet is consistent with good health at all life stages, and may bring some benefits, but the evidence that veganism is a panacea simply isn’t there. It is enough for most vegans, given all the environmental and animal suffering benefits, that we can live more ethically while still being healthy, maybe even healthier if we plan it well. Selling people anything more might give us some temporary vegans, but they might become vocal proponents against veganism when the magic fails to happen or signs of B12 deficiency start to kick in.</p>


<p>Almost everyone can be vegan and most people who become vegan only regret they hadn’t done it sooner, but we have to accept people’s emotional realities. Most of us should probably exercise more, sleep more, learn an instrument and meditate daily. The fact that we aren’t all living our best lives is not always a moral failing, but a reflection of the fact that we have many competing priorities for our energy. Our culture doesn’t always make positive change easy, there are many people and things competing for our mental space and time, and not all of them care about us or the world. Set a positive example, be kind, give people space, and help rather than convince. If you have a choice between dominating an argument or giving a positive impression of veganism, lean towards the latter. As much as we personally identify with veganism, it is not about us or our egos, it is for the animals.</p>
`;


export {
 heading, alternatives, short_answer, long_answer,
};