
const heading = `I am an animal lover`;

const short_heading = `I love animals...`;

const alternatives = `I’d love to be vegan but... I was vegan/vegetarian but…`;

const short_answer = `<p>Noble aspirations are fine, but when we reflect upon our lives, we will judge ourselves more by what we have done than what we wish we had done. In the process of self-actualisation, the most important step is to make our lives consistent with our ethical aspirations. We may love animals or wish there was less suffering in the world, but if we don’t believe these things strongly enough to alter our behaviour, we need to question our ethical priorities. Kind thoughts, prayers, virtue signalling, and policing language can all be reasonable in themselves unless they are the main extent of your activism. Love, compassion and kindness must be active because it is the realm of sentient experience that ultimately matters, not your internal world.</p>`;

const long_answer = `<p>Veganism is an idea that has become more embedded in the mainstream in recent decades. Society has become more conscious, often uncomfortably so, of the ethical conversation around veganism and the treatment of animals. The world was only recently very different. Elder vegans will recount having to constantly explain their veganism at the most basic level; after all, this was a time when most people thought being vegetarian was about abstaining only from red meat. We had to spell v-e-g-a-n countless times; personally, I had to do this almost every time I went out to eat with new people. In developed societies now, most people are at least vaguely familiar with the term. It is now even common to bump into vegans in social situations, along with people who have considered veganism or even tried it. All of these are positive signs that veganism and the ideas it represents are on an upward historical trend.</p>
<p>We seem to be heading, though all too slowly, to the version of the future most vegans believe in: that the moral arc of history will bend towards justice for animals. Most vegans assume that a vegan world is eventually inevitable; that our collective ethical progress will take us beyond the oppression of billions of animals, of forcing them into factory farms and slaughterhouses. We believe that society will eventually be mystified that so many unquestioningly participated in such a vast atrocity. I have watched many eminent ethical thinkers be asked a question such as, &quot;What do we currently think of as normal behaviour in our societies that future generations will look upon as barbaric?&quot; I have seen similar answers from people like Noam Chomsky, Steven Pinker, Martha Nussbaum, and Richard Dawkins, who all said that our treatment of animals was the most likely candidate among our current practices to be condemned by future generations. Sadly, few of these eminent thinkers have followed through with this belief to become vegan or even vegetarian themselves. When I met Peter Singer, I asked him how he felt about his conversation on the topic with Richard Dawkins, and Singer told me how hard it was for him, despite his high regard for Dawkins, to understand his cognitive dissonance in this respect. </p>
<h2>Ethical Consistency</h2>
<p>It would be very inefficient to think through everything we do in our lives; instead, we live mostly through habit and conformity. Most people do this with respect to eating animals; it is something they have always done but have never questioned. Here we get to a moral question: is it worse for someone to do something they know is wrong than to do the same thing without knowing it is wrong, whether that be through ignorance, apathy or some other intellectual mechanism? For the animals, their suffering is the same regardless of the intentions or knowledge in the mind of the person paying for their abuse. We might say someone who worries about the lives of animals in factory farms has a kinder personality, but if they do nothing to help those animals, then their effect upon the world is the same as that of an unkind or ignorant person. If our ethical framework allows us to contribute to animals spending nasty, brutish and short lives in factory farms and slaughterhouses, mainly because we can&#39;t be bothered learning how to eat or cook something else, then it is a very limited ethical outlook. People may look to the norms of the culture around them for moral support, and find justification in the fact that they are only doing what their family, friends, co-workers and much of society do, but ethics is not a popularity contest. The opposite is probably more often true: the most powerful and noble expressions of ethics are when people rejected conformity to the society around them and acted selflessly.</p>
<h2>Moral imperatives</h2>
<p>The fact that more people know about veganism is a good thing. We shouldn’t ignore the positives that this change in the societal narrative represents. Of course, we must try to ensure that the focus is on the animals and not on vegans. Many people will be happier shooting the messenger instead of engaging with the issue the messenger represents, but the opposite of engagement is often not argument, but indifference. Those who are willing to discuss animal rights or veganism, even if they defend a counter position, are in some way our allies in ensuring the topic is in people&#39;s consciousness. We push animal industries beyond the edges of our urban environments, out of sight, out of mind. Truth dies in darkness, and the darkness of factory farms and slaughterhouses is very deep indeed. By encouraging ethical discussion about the status of animals, we do them a service, because so long as it is a rational discussion, it is one we will ultimately win. In this world of minds closed to change, of selfishness and egocentrism, there are people who might be open to a positive change, but we need to make a good case.</p>
<h2>Engaging people</h2>
<p>Hope is often a double-edged sword. If a person starts explaining why they can’t be vegan, most vegans will instinctively want to help the person overcome their hurdles. Of course, the person might be more justifying not being vegan rather than seriously considering veganism, but usually the best policy is to give them the benefit of the doubt. It&#39;s easy to misjudge others&#39; viewpoints and where the other person is in their current outlook; we all fall into stereotypes and assumptions, so we can then misjudge the moment or our tone and come across as preachy or sales-y. Perhaps the first thing to remember is that it is very rare, no matter how well thought-through and expressed all your points are, that at the end of a single conversation, you will have converted someone to veganism. Sometimes being too good at arguing all the points can overwhelm people, and we might be better off listening more and focusing on one or two main points that are most important to the person we are talking to. Having a detailed, conversation-ending answer for every justification you have heard a hundred times before, drowning a person in facts rather than empathy, and ignoring their unique, complex emotional reality can all be counterproductive. We need to have the conversation the person needs and is open to, which helps them change their frame of reference, not the standard conversation we have rehearsed in our minds. We also often embark upon conversations we think would have resonated with us before we were vegan, without recognising that we all have different levels of openness to change in different contexts in our lives. There is not one conversation, but perhaps a different one for each person. It is helpful to remember the statement &quot;We are not our audience&quot;.</p>
<h2>Effective conversation</h2>
<p>What will make people change? When people are asked why they became vegan will often give a very specific answer, for instance, they read a pamphlet, watched a video or were positively influenced by a person. No doubt these were pivotal moments, but there is usually a long process that leads to people being receptive to the right information at that moment. A foundation needs to be laid in each of us, a crack in the conformity of our minds opened for some light to seep in. A different world/self might need to be made conceptually possible before there is a chance for bigger change. Does someone even know about factory farms, or do they assume animals probably have reasonable lives in them, or do they think the way we treat animals might be wrong but don’t know what to do about it, or are they vegetarian because they instinctively think killing animals is wrong but don’t properly understand the death and suffering in the egg and dairy industries, or are they attracted to the idea of veganism but just need to know what steps to take, or something else unique to them. Chances to sincerely discuss our relationship with the non-human world are precious; we should not squander them with the discussion we want to have, circling debate, or giving people information overload. We have to focus on the person in front of us and how we can help their ethical journey, even if they don’t know they are on one.</p>
<p>Communication is hard because people are complex and unique; they are often so very different from us as to be almost unrelatable. Drawing broad lines here, some people will judge a discussion by its rationality; they are best reached via a clear, coherent argument, and too much emotion will make them feel they are being manipulated. Others are more sensitive to the interpersonal aspects of a conversation, too little emotion might come off as cold, facts aren’t inconsequential, but an emotional connection with them, and animals are more likely to resonate. People have different life experiences, cultures, sensitivities, and levels of tolerance for difficult topics. People also have psychological defence mechanisms, and many will instinctively turn away from discussions or depictions of suffering, perhaps as echoes or reminders of their own pain or trauma. So some people might be willing to hear the full horrors of animal farming, and others might need more of a focus on the positive alternatives to animal farming. People are also at different stages of knowledge about issues and varying openness to change; in short, some need to know why, but others need to know how. Blundering into a system as complex as the human mind without understanding it is usually a mistake. If someone says &quot;I can’t be vegan&quot;, we have to start by listening.</p>
<h2>Vegans and ex-vegans</h2>
<p>One place where many passionate vegans can be short-sighted is in their attitude towards people who used to be vegan. “They were never really vegan” is almost a cliche in such situations. This way of thinking ignores many realities and circumstances in people’s lives. The most obvious is that sometimes people need a few attempts at making life changes, even ones they want and believe in. Perhaps people were undergoing something emotionally challenging while they were trying to become vegan, and might just need some healing and re-energising before they will be ready to try again. People’s motivations for going vegan also vary. Not everyone becomes vegan for animal rights or from a reverence for the non-human world. Some come to it for health, or because they were in a relationship or social circle that made it easy for them to be vegan. They might not see stopping being vegan as betraying the animals, because for them, it was never really about the animals in the first place. The attrition rate of vegans, especially those who aren’t motivated by ethical considerations, is high. When someone is vegan, many in the movement kind of think of that as a &quot;tick&quot;, and if we focus on them at all, it might be about how we get them to become activists. Our movement focuses too much on getting people to become vegan and doesn’t do enough work on helping already existing vegans to be happy, healthy, socially connected and well-informed. Speaking about social connection, not all social circles are as tolerant of veganism as they should be. If someone is the only, or one of the only, vegans in their family, social circle, relationship, workplace or community, it is going to be harder for them to stay vegan than for others. We need to think about how we can help people foster a community that makes it easier for them to make ethical choices without negative social ramifications. Just being around a group of kind, committed vegans every now and then can be a balm for many people; it can help them feel less alone and different in the world.</p>
<h2>Over promising</h2>
<p>With health, a lot of vegans can promote unrealistic claims for the vegan diet. Literally, people will say that vegans never get sick.  When I posted on social media that I was getting the COVID vaccine, someone commented that I should be immune to viruses because I was vegan. Some people don&#39;t even advocate taking a regular B12 supplement or making sure to eat calcium and omega-3-rich plant foods. Not only are these positions dangerous and empirically untrue, but promoting veganism as a miracle cure can lead to disappointment and disillusionment. The highest nutritional bodies in the world reaffirm that a well-planned vegan diet is consistent with good health at all life stages, and may bring some benefits, but the evidence for veganism as a panacea simply isn’t there. It should be enough to know, given all the environmental and animal suffering benefits, that we can live more ethically while still fulfilling our health needs, and can maybe be even healthier if we plan our diet well. Selling people a miracle cure might gain some temporary vegans, but they might also become vocal proponents against veganism when the magic fails to happen, or signs of some nutrient deficiency start to kick in. We want a movement for the long haul, and that means preferring to make long-term vegans over short-term victories.</p>
<h2>Conclusion</h2>
<p>Most people who become vegan only regret they hadn’t done it sooner, so we think people should get on board the vegan bus as soon as possible. Yes, people should go vegan, but most of us should also probably exercise more, sleep more, learn an instrument, use less plastic, ride a bicycle and meditate daily. The fact that we aren’t all living our best lives is not always purely a moral failing, but a reflection of the fact that we have many competing priorities for our physical and mental energy. Our culture doesn’t always make positive change easy; there are many people and things competing for our mental space and time, and not all of them care about us or the world. As vegans, we might need to be patient and consistent in setting a positive example, being kind, giving people space, and helping rather than convincing them. If you have a choice between dominating an argument or giving a positive impression of veganism, you might think about leaning towards the latter. </p>
<p>As much as we personally identify with veganism, it is not about us or our egos; we are speaking for the animals, and we have a responsibility to do it effectively. Some of the most vociferous, hardline vegans I have met seemed to put more people off veganism than draw them to it. Being right, coming from the moral high ground, is not enough; our egos can often be the main barrier between us and our connection with others. Almost any conversation about veganism is a chance to plant seeds that might bear fruit. Let us ensure in these conversations, we properly embody our message by exhibiting the compassion for humans that we are trying to promote towards animals.</p>`;

export {
 heading, short_heading, alternatives, short_answer, long_answer,
};
