// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `I'd love to be vegan, but..."`;

// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `I was vegan/vegetarian but...`;

// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `Many people consider diet solely an individual choice, ignoring the power of our collective choices that make the world. The factory farming industry overruns and degrades much of the arable earth whilst causing animal suffering and a host of other problems. When someone explains why they can’t be vegan, they often minimise the reality of animal farming or offer some idealised version of it. There is too much suffering in the world and reducing our usage of animal products reduces our contribution to this unfortunate reality. Veganism is a powerful, positive step most of us can take towards a kinder, healthier and more beautiful world.`;

// This is the body of the individual page, use html liberally.
// Format: HTML.
const long_answer = `
<p>The more mainstream veganism becomes and society begins to understand some of the multitudes of reasons for being vegan, the more we hear people say “I would like to be vegan, but…”. People who have been vegan for a while remember conversations used to mainly involve explaining what veganism or even vegetarianism is. I’ve personally had to spell out the word countless times. People being familiar with the term, let alone having engaged with or considered veganism, is a positive sign that veganism has entered the mainstream consciousness.</p>
<p>Still, maybe on some level, it is easier to forgive someone not embracing a concept they weren’t aware of than someone who is aware of it and has for some reason rejected it. It can be a little emotional for a vegan to hear. In this world of minds closed to change, of selfishness celebrated as personal empowerment, it can spark hope when someone expresses that they are even open to positive change. A passionate vegan’s pulse might quicken a little seeing this glimmer of hope for animals and the environment. Maybe, if we can just say the right thing, we can do some powerful good for animals and the world.</p>
<p>Hope is often a double-edged sword. A vegan advocate will want to launch into a conversation to help the person over any hurdles they have, to understand if they need more cooking tips, ideas for eating out, nutritional information or an understanding of the philosophy of animal rights. If we misjudge the moment or our tone these conversations can come across as preachy or “salesy”. We might forget that people rarely change their beliefs during a single conversation, no matter how well constructed. Changes to deeply held beliefs often happen gradually, a journey to a new vision constructed step by step, and the decisions to change most often happen in moments of quiet reflection with our own souls. Having a detailed answer for every question, because you have heard a hundred times before, drowning a person in facts rather than help, and ignoring their unique complex emotional reality, can all be counterproductive. We need to have the conversation the person is open to, that helps them change, not the one we have rehearsed in our minds, which might have changed us.</p>
<p>Communication is hard, partly because people are so unique, often so very different from us as to be like another species. Some people will judge a discussion by its rationality, they are best reached via a clear coherent argument and too much emotion will make them feel they are being manipulated. Others are more sensitive to the interpersonal aspects of a conversation, too little emotion might come off as cold, facts aren’t inconsequential but empathising with animals is more likely to resonate with them. People have different life experiences, cultures, sensitivities, levels of trauma and tolerance for difficult topics. People have psychological defence mechanisms and many will instinctively turn away from discussions or depictions of animal suffering, perhaps as reminders of pain or trauma they have experienced. People are also at different stages of knowledge about issues and varying openness to change. Some people need to know how, others why. For some, we must start at basics and introduce ideas, helping them see that another world is necessary or even possible. Blundering into a system without understanding it is usually a mistake, especially in systems as complex as human lives. When someone says they can’t be vegan, we have to start by listening and learning, and perhaps focus not on convincing them, but on how we might help them.</p>
<p>One place many passionate vegans can be short-sighted is in their attitude towards people who used to be vegan. “You were never really vegan” is the cliched comment made in these cases. This way of thinking ignores many realities. The most obvious is that people often need a couple of attempts at making life changes, even ones they believe in. People’s motivations also vary. Not everyone becomes vegan for animal rights or from a reverence for the non-human world. Some come to it for health, or because they were in a relationship or social circle that made it easy for them to be vegan. The attrition rate of vegans, especially those who aren’t motivated by ethical considerations, is high. Sometimes our movement focuses too much on getting people to become vegan and doesn’t do enough work on helping already existing vegans to be happy, healthy and educated. It’s usually easier to conform in life, people have a deep need for social connection, and not all social circles are as tolerant of veganism as they should be. People have a deep need for connection with others, and as vegans, we need to think about how we are helping foster community that helps people make ethical choices without negative social ramifications.</p>
<p>With health, a lot of vegans (often new vegans) promote unrealistic claims for the vegan diet, literally that you will never get sick, or become immune to viruses, they don’t even advocate taking a B12 supplement. Not only are these simply empirically untrue, but promoting veganism as a miracle cure can lead to disappointment and disillusionment in people who come to it with that motivation. The highest nutritional bodies in the world reaffirm that a well-planned vegan diet is consistent with good health at all life stages, and may bring some benefits, but the evidence that it is a panacea simply isn’t there. It is enough for most vegans, given all the environmental and animal suffering benefits, that we can also be healthy on a vegan diet, maybe even healthier if we plan it well. Selling people anything more might give us one more temporary vegan whilst setting them up for potential long-term disappointment.</p>
<p>So yes, most people can be vegan and we know many people who become vegan only wish they had done it sooner, but we have to accept people’s emotional realities. We all also wish we were exercising regularly, sleeping more, and learning an instrument. The fact that we aren’t all living our best lives is not always a moral failing, but a reflection of the fact that we have many competing priorities for our energy in a world that doesn’t always make positive change easy. Be kind, and give people space. If you have a choice between winning an argument or giving a positive impression of veganism, choose the latter, for the animals.</p>
`;

export {
  heading,
  alternatives,
  short_answer,
  long_answer,
};
