
const question = `Mmmm bacon...`;

const short_question = `Mmmm bacon...`;

const alternatives = `"I love steak" is almost as common. Other lines from the toxic masculinity script.`;

const summary = `<p>Saving &quot;steak&quot; or &quot;bacon&quot; to someone vegan is meanness in the guise of humour. We tend to think of humour and laughter as positive human expressions, but they are actually a complex part of communication. Laughter can be joyous and sincere, or fake and hollow. Sometimes we can&#39;t help but laugh, sometimes we force out a chuckle, and sometimes people engage in fake performative laughter. The latter sort of laughter can be part of status displays, or of declaring our identity with a person, group or mob. One shouldn&#39;t look for much emotional depth in people prone to a lot of fake laughter. Humour that relies on cruelty or meanness reveals the character of both the instigator and those who laugh along. Such people are to be ignored or avoided, certainly not worried about too much, because being a fake person is its own karma.</p>`;

const discussion = `<p>There can be good jokes that make light of veganism, even some jokes that vegans will tell among themselves. Like any type of joke, these jokes can be clever, surprising, or interesting. Then, however, there are attempts at jokes that have no positive qualities, usually told by people who also have no positive qualities. I&#39;ve attended many protests against animal cruelty where people, almost always young men, will walk past and say, “I like bacon”, “I&#39;m going to have a steak”, etc. They are statements that anyone who has done much public animal activism will have heard repeatedly, beyond all tolerance for boredom. The people who say such things will repeat these phrases with the seeming pretence of having thought of it themselves. It is unlikely, however, that these sort of people have ever added an original thought to our culture. Jokes, and just for convenience, we will call these boorish ejaculations jokes, don&#39;t get funnier with repetition, in the same way that repetition doesn&#39;t make lies become true, or stupid statements intelligent. </p>
<h2>Ugly humour</h2>
<p>Human laughter is complicated, and science struggles to understand all of the many reasons people laugh. Plenty of animals laugh as well, though seemingly for simpler expressions of joy or communicating that they are playing. What is clear is that people often laugh at things not because they are spontaneously funny but because they want to laugh for performative social reasons. This kind of laughter often sounds fake, like a jarring echo from a hollow, unkind place. Fake laughter sounds like someone read in a book what a laugh was and is trying and failing to capture the essence of it. You can sort of tell ugly laughter by the way it is forced out, when someone is trying to assert superiority over someone, or put them down; what we call &quot;laughing at&quot; rather than &quot;laughing with&quot;. Laughing at others&#39; misfortunes is correlated with psychopathy and other destructive and self-destructive personality traits. We can argue about what things are OK to joke about, and I personally enjoy a dash of schadenfreude in my humour, but jokes that reinforce existing evils in the world, that have victims, need to be held to a higher standard. Humour, perhaps especially dark humour, can make light of dark times and places. It can help us deal with painful or uncomfortable things without having them overwhelm us. The rich, deep humour of some Holocaust survivors is evidence of this. Sometimes it is life-affirming to laugh when the alternative is to cry, or laugh when we don’t think we should. We can take all of the world’s ugliness and misfortune and find something to smile about in it. </p>
<p>Humour, or the pretence of it, isn&#39;t inherently moral or immoral. In addition to easing our load, humour can be used to bolster oppression and cruelty. A smile can be a leer, a smirk or a sneer; it can be a mask hiding the mob&#39;s ugly face. Humour can be used by the angry, irrational part of us to drown out the quiet voice of the intellect, of introspection, empathy and subtle thoughts. Sartre famously said, &quot;Hell is other people&quot;, but hell is only some other people, and a sign of this sort of person is how much of their humour is jeering and ill-intended. Witness how the laughing emoji on social media started out as a positive expression, but has since been used and abused by conspiracy theorists and trolls who need to mock better people than themselves.</p>
<h2>Humour and empathy</h2>
<p>Psychologically, there is something called a cold joke. It&#39;s been witnessed in atrocities towards humans for centuries. People who are perpetrating immoral acts, killings, torture and the like, use the pretence of humour to avoid the other psychological ramifications of something disturbing they are participating in. They bond using jeers and fake laughter with other damaged souls, exhibiting the same insincerity and toxic emotion that probably defines all of the relationships in their lives. If someone can laugh about atrocities like billions of innocent creatures suffering in factory farms and dying in slaughterhouses, and if they see a person caring about those lives as weak or pathetic, we might ponder how capable they are of true, empathetic connection with any other sentient being. Would such a person be able to love anyone else fully and selflessly in their lives? We might even pity the shallowness they wear so proudly, because emotional connection, the ability to empathise and care for others, to be vulnerable and trust others at a deep level, is among the things that most give life beauty and meaning.</p>
<p>Pigs, sheep, goats, chickens, cows: We can recognise something of ourselves when we look into the eyes of another sentient creature. These are thinking and feeling beings we share our evolutionary kinship with, who seek to be happy as we do, and we can see that when we look in their eyes. More animals suffer and die in our industrial prison systems every week than all the humans who have been killed in wars during our bloody history. In modern times, we outsourced our killing to other people, usually poor and disadvantaged slaughterhouse workers. We have pushed the sight, sound and stench of killing to the outskirts of cities. In the ever more intense push for corporate profits, a system of animal confinement has been created that is intolerably cruel. For most of history, people lived closely with wild animals and felt a kinship with them. They knew that the animals around them had family and relationships of their own, that they were intelligent, and worthy of respect. Even when they needed to kill them to survive, they would often apologise to them and thank them for their sacrifice. That respect has been replaced by the morality of what is out of sight is out of mind. We now mock the animals we rely upon by using their names as insults. What has become of us? </p>
<h2>Wanting to believe</h2>
<p>Those who pay for this terrible industry have hands indelibly stained by blood they don’t wish to see. We can start on repairing their relationship with the non-human world by at least showing respect for the lives of animals. The beings we force to live in lightless sheds, in cages, taken from their families, and line up for their turn in slaughterhouses, are not simply a mass product. They are individuals, someone with their own personality, relationships, desires and purposes. These lives and deaths over which we wield god-like power can, according to our choices and whims, be either terrible or bearable, imprisoned or free. Motherhood, love, friendship, society - part of the reason we so easily rob other creatures of these experiences is that many myopically think of high emotions as uniquely human, but this is false. All animals evolved from a single ancestor, but mammals are our especially close evolutionary kin. Much of how they interact with and process the world is similar to ourselves, and we know this when we interact or play with them, but selectively choose to forget it when eating them. Studies show that if you ask a person about the internal lives of animals, they rate animal sentience much lower if they are eating an animal product at the time, and higher if they are eating some other snack. How much animal suffering has gone on because of our selfish need to deny their ability to suffer?</p>
<p>If humans actually had to eat animals, if there was nothing else we could survive and thrive on, then ethics would still demand a radical overhaul of our farming system. However, we are omnivores who can eat a wide variety of foods; therefore, eating animals is a choice we can make and unmake. The world will be a better place when animals are no longer the intended victims of our food system. The alternative to a plant-based diet is playing a greater part in oppression. Instead of trying to feel better about our involvement in killing animals by saying something cruel and offensive, and pretending that boorishness is funny, we could take a more heroic stance. </p>
<h2>A kinder path</h2>
<p>Hopefully one day keeping animals in factory farms will be illegal, but currently, people have the choice to do so and pay for others to do so. To choose to treat other beings as purely a means to our ends, whether for food, entertainment, clothing or other consumer goods, is a barren, life-diminishing choice, even if we aren&#39;t making it consciously. The less ethical and open-minded people are, the more tightly they will cling to this choice and try to hamper anyone on a nobler path ahead of them. Indeed, such people are obsessed with status, and especially the idea that anyone thinks they are better than them. It is sad to see people trapped in prisons of their own habitual mediocrity, so unable to imagine a different self that they fear escaping. It is a poor use of the possibilities of life, peering out suspiciously at the world, at difference, fearing change and growth, despising anybody who reminds us by word or example that there are kinder and better ways we can live. The simple truth is that when people are mocking others, they at least aren&#39;t thinking about their own flaws, limitations and failed dreams. There is, however, a better way, one that leads to our flourishing. In a world full of expansive, beautiful possibilities for our relationship with other life, why wouldn&#39;t we want to spend our time treading a kinder path? There are many great deeds needing to be done to heal the world, things that can challenge us to embody our highest selves and collective flourishing. The animals and the world need heroes now as much as ever. </p>
<p>The greatest potential a person can try to fulfil is their ethical potential. As for animals, most of us have room for improvement. While we confront the darkness and suffering of life, even our own limitations, humour can be a balm that helps keep us motivated and sane. Laughter is a mysterious gift in life, and life is too short to squander that gift on fakeness and meanness. Let us all laugh less often at others, and more often at ourselves.</p>
<p>Finally, a joke about carnists I hope they can appreciate: How many meat eaters does it take to change a lightbulb? None, they prefer to stay in the dark.</p>`;

export {
 question, short_question, alternatives, summary, discussion,
};
