
const heading = `But you can't eat that!`;

const short_heading = `You can't eat that`;

const alternatives = `It's not vegan, but it is gluten-free. Can you eat bread, peanut butter, etc?`;

const short_answer = `<p>Non-vegans and new vegans focus on what vegans don&#39;t eat, whereas established vegans mostly focus on what they do eat. From the perspective of an animal-product-heavy diet, veganism may seem like a diet of self-denial. Vegans, however, see aligning our consumption with our compassion as the opposite of self-denial because it is about living in a way that expresses our better selves. Replacing a handful of ingredients is a small price to help heal humanity&#39;s relationship with the non-human world. Once we become accustomed to being vegan, a mental shift occurs where we cease to consider animal products as food and instead focus on the infinite variety of the world&#39;s foods and cuisines.</p>`;

const long_answer = `<p>Some vegans like myself weren&#39;t looking for an identity or a belief system; indeed, I didn&#39;t really mean to become vegan. I stopped eating animal products one at a time, as I found out about the cruelty inherent in each of them in turn. Refraining from eating them was the result of a deliberative process and conscious decisions, not an attempt to become &quot;vegan&quot;. Nothing stops me from eating animal products, as embodied by the word &quot;can&#39;t&quot;, except my concerns for the animals involved. Perhaps this seems like nitpicking; &quot;can&#39;t&quot; is only a word, but the fact that it is so often chosen over other alternatives seems to reveal that people are missing an important point. The choice of words may seem subtle, but it&#39;s important to frame veganism as an active, ongoing, thoughtful, powerful set of choices.</p>
<p>Something in the phrasing of the statement &quot;You can&#39;t eat that&quot; is revealing. After you have heard this phrase enough times, you start to wonder why people so commonly frame vegan dietary choices with the word &quot;can&#39;t&quot;, rather than &quot;won&#39;t&quot; or &quot;don&#39;t&quot;. The use of &quot;can&#39;t&quot; turns the phrase into something that sounds involuntary or not thought through. There are people who &quot;can&#39;t&quot; eat things, such as people with allergies, intolerances or taste aversions, but vegans are none of these. There are those who &quot;can&#39;t&quot; eat something because of the belief that doing so would cause them to fall out of favour with one or another higher power, or at least their community. This kind of performative renunciation or aestheticism, too, is not what veganism is about. Most vegans have eaten animal products at some point in their lives, so they certainly can eat them, but have consciously chosen not to.</p>
<h2>Personal choices</h2>
<p>Veganism is about our relationship with animals, not vegans. It isn&#39;t about &quot;personal&quot; choices, but rather the opposite. Veganism is about starting to take responsibility for the world beyond ourselves, and our contribution to suffering in it, certainly not purity or blind adherence to an arbitrary set of rules. Our “personal” consumption choices are rarely personal, as they ripple outwards into the world. Choices are certainly no longer personal when they have victims. What we “can’t” do is separate our lives and actions from all other life, for we are locked in an interdependent relation with it, one in which, as a human, we have inordinate power. In making choices about what to eat, we regularly and powerfully affect the world and the lives of others. If we could trace the origins of all the ingredients on our plates over the average week, they would span a vast area of the earth, involving thousands of individuals and complex processes to bring them to you. The sheer scale of agricultural corporations that feed billions of people every day means that there are many potential ethical concerns involved. The ethics of how we eat is a complex intersection of corporations, governments, billions of consumers, millions of producers, countless wild and farmed animals, and our global environment. The decision to follow a vegan diet is perhaps the most powerful way to claim our power and responsibility within this complex system.</p>
<h2>Defining veganism</h2>
<p>What exactly is a vegan diet, though? What do and don&#39;t vegans eat? The original Vegan Society, based in England, has a statement that most vegans take as the de facto definition:</p>
<p>&quot;Veganism is a philosophy and way of living which seeks to exclude—as far as is possible and practicable—all forms of exploitation of, and cruelty to, animals for food, clothing or any other purpose; and by extension, promotes the development and use of animal-free alternatives for the benefit of animals, humans and the environment. In dietary terms, it denotes the practice of dispensing with all products derived wholly or partly from animals.&quot;</p>
<p>This statement is an excellent start, but it also needs to be thought through by each person. The Vegan Society, in its early days, didn&#39;t consider honey to be vegan. They then changed this stance and declared it a matter of individual conscience, but they then returned to not considering it a vegan product in the 1980s. This may even change again as more humane techniques for farming bees in the future are created. Veganism exists within a changing world, with cell-cultured meats, precision fermentation, new farming techniques and even the accuracy of many “mock” products creating an ever-evolving discussion about what should and shouldn’t be called vegan. Veganism must evolve as the world evolves, and not make the same mistake that many religions have, of fixing their morality at a point in time or on a set of ideas that lose relevance as the world around them changes.</p>
<p>As corporations that profit from factory farming diversify into the growing vegan market, it continues to complicate the ethics of food choices. Some vegans won&#39;t buy products from companies that get most of their income from animal products, while others see this as a way of incentivising those companies towards more ethical production. Palm oil production, or other products that cause major species loss and deforestation, are not considered by many to be consistent with veganism. Others see environmental concerns, or concern about a relatively small number of wild animals compared to the lives of billions in factory farms, as being of lesser ethical importance. This is one of many ongoing debates about antinomies within the vegan community, with compassionate and sensible people on all sides. People who are unfamiliar with the diverse intellectual landscape of veganism often speak quite clumsily about it in black and white terms, such as &quot;can&quot; and &quot;can’t&quot;, but there are few ethical sharp lines in a changing and complex world.</p>
<p>There are people who intellectually agree with all the arguments about the ethical necessity of veganism, but think that a moratorium on eating animal products doesn’t always achieve the best outcome for animals. Some of these people call themselves “freegans”, people who combine vegan ethics with the vital issue of food waste. While a freegan will only purchase vegan products, they will eat animal products that would otherwise be discarded. This is often the motivation behind <strong>dumpster diving</strong>: rescuing and repurposing the vast amount thrown away by businesses, often when they pass or near an arbitrary “best before” date, etc. Environmentally and ethically, there is no benefit to discarding something when all the misery and resource expenditure involved in its production have already happened. So long as you are not helping create a market for it, you are reducing your environmental and ethical footprint by consuming it. While I admire freegans, like many long-term vegans, I no longer consider animal products to be food, and the idea of eating them provokes a disgust response.</p>
<h2>Delving deeper</h2>
<p>To complicate our ethical considerations further, there are people who call themselves ostro-vegans. Ostro-vegans consider only sentience - the level of conscious awareness and ability to experience things like pleasure and pain that a being has - as a factor in the ethics of their consumption. The terms plant and animal seem pretty clear in our minds, but evolution is more subtle than such black-and-white terms can encompass. Evolutionary science points towards a vast, complex web of interrelated life existing on many continuums. As far as we know, there is only one family of life on Earth; animals evolved from plants, and there are endless forms of life at each stage in this progression, both in terms of physical and mental attributes. Ostro-vegans delve into the blurry lines between species, between plants and animals, sentient and non-sentient, and draw the line of compassionate duty differently than vegans do. There are creatures called bivalves, such as clams and mussels, that lack a centralised brain. They can make simple movements such as opening and closing their shells, but don’t appear to have any of the internal wiring needed for consciousness. Do these seemingly simple creatures require the same moral consideration as clearly sentient beings such as pigs, chickens, cows, and tuna? Ostro-vegans consider it ethically acceptable to eat bivalves, and perhaps find it an easier diet to follow than veganism, especially in terms of social conformity. Although they don&#39;t see the need to eat these animals, many vegans are sympathetic to the ostro-vegan approach as more ethical and considered than that of most others.</p>
<p>The journey towards an ethical life is similar to climbing an unfamiliar mountain: You see a peak above you, you climb towards it, and just as you think you are about to reach the summit, another previously obscured peak appears above. Veganism is not about ticking a list that offers ethical purity, but rather a path where we hope each step gets us closer to an ethical life than we were before. Veganism is about trying to make the world kinder for all life, not about self-denial or moral purity.</p>
<p>When people start on the journey of veganism, they will often accidentally eat an animal product. &quot;Why has this got milk solids in it?&quot; is a phrase one often hears from incredulous new vegans about products they wouldn&#39;t expect to have dairy in them. Sometimes, even when one has been vegan a long time, through accident or complacency, eating some animal product unfortunately happens. Some people get upset about this more than others, but from the viewpoint of the universe, the ethics are less relevant. We should focus on what we do and consume 99.9% of the time, rather than expending too much energy on the final 0.1%, unless, of course, we enjoy doing so. It is the totality of our life that is important, not the occasional, inevitable errant step. We learn, we move on. Of course, there are those who deliberately eat specific animal products and refer to themselves as a vegan. Some see this as harmless, but I would say that the word &quot;Vegan&quot; has to mean something. When I say I am vegan in a restaurant or other setting, the cooks and chefs should have a clear idea of what that means. The definition is simple: no animal products, and cooks shouldn&#39;t have to have a twenty-minute conversation with each consumer to find out what it means to them. Though I do not think veganism should be overly dogmatic, neither should it allow itself to become a vague, meaningless term. Veganism is a clear political statement to others about our ethical stance towards animals. It is important to display an ethically consistent message, a clear narrative light, for people to follow. Hypocrisy is often the easiest and most damning way that moral authorities have been undermined in the past. What we say about ourselves, what we ask of others, should be consistent and clear. Whatever label someone attaches to themselves, vegan, vegetarian, pescetarian, freegan, ostro-vegan, or some other, they become a representative for that idea in the world. We all have a duty to represent the ethical labels we claim in a way that serves wider and higher purposes than ourselves.</p>
<h2>Peanut butter?</h2>
<p>Finally, for vegans there is a pretty simple test. Is it from an animal? Then don&#39;t eat it. For some reason, this is much more complicated in many people&#39;s minds. Some of the things that people regularly eat, but have never thought of as vegan, can be amusing. I’ve had all manner of things I eat be questioned as to whether they are vegan, including bread, pasta, beer, avocado, oat cream and peanut butter. This partly shows how little people understand their food, especially its ethical aspects. People conform; they accept the food their culture and family serve up, and don’t question it. They often don&#39;t even know in much detail what ingredients or nutrients are in the foods they eat, much less the repercussions of their diet on the world. No one is born with this sort of knowledge; they must acquire it somehow, so only education can correct this. If we find people with relatively open minds, starting discussions about food and ethics will be good for them, animals, and the environment. We should start with the things we all have in common. Most people don&#39;t want to hurt animals or the environment. Most people, especially people following a relatively healthy diet, will already be deriving the majority of their nutrients and calories from plant foods. By starting to make the unfamiliar familiar with what vegans eat, we can start to give people another possible conception of their diets and themselves.</p>
<p>Focusing on what vegans can and can’t eat mistakes the forest for the trees. Veganism is not a diet; it is a philosophy of compassion. People who mistake veganism for a diet display how little they understand its vital message for our world. Veganism is not about ticking some arbitrary boxes; it is about having a thought-through personal response to deep ethical questions about the way humans currently treat other life. What we &quot;can&#39;t&quot; do collectively is continue living in a way that depletes the shared living systems of this world. What we &quot;can&#39;t&quot; do is continue sending animals into slaughterhouses and factory farms, and think our ethics towards animals shouldn&#39;t be questioned.</p>`;

export {
 heading, short_heading, alternatives, short_answer, long_answer,
};
