// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `But you can't eat that`;


// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `Can you eat bread? Or some other thing they assume isn’t usually vegan."`;


// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>From the perspective of an animal-product heavy diet, veganism may seem restrictive; that vegans “can’t” eat many things that people consider the centre of their diet. Aligning our consumption with our compassion is actually the opposite of self-denial, it is about the ongoing daily expression of our best self. Abstaining from a handful of ingredients is a small price to pay to help restore our relationship with the non-human world.</p>`;


// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>It is interesting that people commonly frame vegan dietary choices with the word "can't". It sounds almost as if it is not a voluntary choice, but something like an allergy or a religious duty. It’s only a word, generally used with little thought, but it grates a little to the ear. Veganism is not about what we can and can’t do, but what we will or won’t do. It’s a subtle difference, but one that frames veganism as an active, ongoing, thoughtful, powerful choice. Most vegans don’t see being vegan as a “personal” choice, it is about reducing suffering in the world rather than anything about us personally, certainly not purity or blind adherence to an arbitrary set of rules.</p>
<p>Our so-called “personal” consumption choices ripple outwards. Eating is one of the ways we most regularly and powerfully affect the lives of others. If we could trace the origins of all the ingredients on the average dinner plate, they will often span the globe, involving thousands of individuals and complex processes to bring them to you. The sheer scale of the corporations feeding billions of people every day means that there are many potential ethical concerns towards the environment, animals and humans. The choice to follow a vegan diet is perhaps the most powerful response to many aspects of this.</p>
<p>What exactly is a vegan diet though? The original Vegan Society based in England has a definition that most vegans take as the official definition:</p>
<blockquote>"Veganism is a philosophy and way of living which seeks to exclude—as far as is possible and practicable—all forms of exploitation of, and cruelty to, animals for food, clothing or any other purpose; and by extension, promotes the development and use of animal-free alternatives for the benefit of animals, humans and the environment. In dietary terms, it denotes the practice of dispensing with all products derived wholly or partly from animals."</blockquote>
<p>Officially the Vegan Society doesn’t currently consider honey vegan, however, this wasn’t always the case and they have actually gone back and forth on this at least once over their history. It’s possible more humane techniques for farming bees in the future might change this again, or technology might give us the ability to make cheaper, biologically indistinguishable honey by other means. Veganism would not want to make the same mistake that most religions have, of fixing their morality at a point in time that loses relevance as the world around them changes.</p>
<p>Cultured meat, precision fermentation and pretty convincing “mock meats”, all make the idea of what is and is not an animal product more nuanced. As corporations that profit from factory farming diversify into the growing vegan market as well, it complicates things further. Some vegans would prefer not to buy products from companies that also profit from selling animals, while others see it as a way of incentivising those companies to move to more ethical production. Palm oil production, or other products which cause deforestation in environmentally sensitive ecosystems, are seen by many vegans, especially ones concerned about the environment, as not being consistent with a vegan ethic. Others see environmental concerns, or the concern about a relatively small number of wild animals, in comparison to the lives of billions in factory farms, as being of less ethical importance. There are many active and ongoing debates about issues within the vegan community. People not immersed in the ethical considerations around veganism often speak quite clumsily about it, "can" and "can’t", but there are few sharp lines in ethics.</p>
<p>There are people who agree with all the arguments about the positive ethics of a vegan diet, but think they don’t actually go far enough. Some of these people call themselves “freegans”, who also engage with the globally relevant issue of food waste. In addition to only personally purchasing vegan products, freegans will eat animal products that would otherwise be discarded, such as the vast amount thrown away by businesses when they near an arbitrary “best before” date etc. Environmentally and ethically there is little good in discarding something when all the misery and resource expenditure has already happened, so long as you are not helping create a market for it. For many vegans, the idea of eating an animal product provokes a disgust or “creepy” response in them, but they are in profound agreement that Freeganism is an ethical response to the world.</p>
<p>To complicate matters further there are people who called themselves ostro-vegans. They consider only sentience - the level of conscious awareness and ability to experience things like pleasure and pain that an individual has - in their consideration of what can be ethically consumed. The terms plant and animal seem very clear in our minds, but if we understand the basics of evolutionary science, that life is a vast interrelated tree, we’ll understand that these terms are overly simplistic. Animals evolved from plants, and there are endless forms of life at each stage from microscopic zooplankton to blue whales. Ostro-vegans delve into this blurry line between plants and animals, sentient and non-sentient. Do creatures that can’t move and don’t appear to have any of the internal wiring needed for consciousness such as clams and mussels require the same moral consideration as clearly sentient beings such as pigs, chickens, cows and tuna? Ostro-vegans think that it is ethically acceptable to eat these simpler beings, and perhaps find it a more attractive diet to follow than strict veganism. Many vegans are sympathetic to this logic, even if finding it irrelevant as their vegan diet already fulfils their nutritional and culinary needs.</p>
<p>Part of the many journeys in life, especially the ethical one, is finding that whatever stage we get to there are usually further steps we can take. Veganism is about making the world better, not self-denial or moral purity. If we accidentally eat an animal product, it is not really that ethically relevant, it is what we do 99.9% of the time that matters. But as much as veganism would not want to be seen as overly dogmatic, we should remember that is also a political statement to others about where we stand in the world. Whether we want it or not, our actions and our example often have a powerful positive or negative effect on the world. There is much to be said for displaying ethical consistency, and for providing a clear narrative light for people to follow. There are also perceptions of hypocrisy that will undermine our moral authority if we seem to ask of them things we don’t always do ourselves. Whatever label you present to others, freegan, ostro vegan, vegan, or some other, whether you ask for it or not you are now a representative of that idea in the world. Whilst it is good to make clear what we aspire to ethically, we should also be clear to express our limitations, flaws and weaknesses, and no doubt this will create much more empathy with and connection to others as we try to communicate our message.</p>
<p>Finally, the second point is about people thinking vegans can't eat things that are usually vegan but not labelled as such. I’ve had bread, pasta, avocado and peanut butter...I guess it does have butter in the name. This partly shows how little people are engaged in their diet, they just accept what they are served up, what their parents served up and don’t really know what is in the foods they eat much less their repercussions on the world. If someone is open to discussion, it is a good chance to open their mind, especially to the fact that the basis of most people’s diets is already mostly vegan. This is especially true if they are eating healthily. However, to some people it is an opportunity to argue, and to the waitress who served us in West End all those years ago, you may work at an Italian restaurant and think you are an authority on the matter but pasta can definitely be, and dried pasta usually is, vegan.</p>
`;


export {
 heading,
 alternatives,
 short_answer,
 long_answer,
};