
const question = `I could never give up cheese`;

const short_question = `But cheese`;

const alternatives = `I could never go vegan because… but you won't need any other alternative because you'll be hearing about cheese repeatedly.`;

const summary = `<p>Cheese is mostly about two things: fat and cruelty to animals. By giving it up, you will reduce both your fat intake and your contribution to suffering. More than other animal products, people say they feel better after giving up dairy. This is unsurprising, as only a third of people globally have the genetic mutation necessary to process lactose beyond infancy. Like all other mammals, humans are naturally weaned from their mother&#39;s milk after infancy. The experience of expressing and imbibing milk evolved as part of the intimate relationship between a mother and her child. For humans to interfere with this, to commercialise the pregnancies of other species, is oppressive…and a bit creepy.</p>`;

const discussion = `<p>The statement &quot;I could never give up cheese&quot; implies an unspoken corollary: &quot;I don&#39;t care what cruelty or environmental destruction is involved in producing it&quot;. Hopefully, most people are better than this, and there is a line of cruelty towards animals that they would not cross. Would many people really continue drinking dairy if they became convinced it was both unnecessary and intolerably cruel? Assuming that we can prove that the dairy industry is intolerably cruel, surely people could find enough self-control and compassion for other species within themselves to make a positive change. </p>
<p>The problem is that few people who drink dairy know, or wish to know, the truth of the industry they support financially. If they educated themselves about the bereaved mothers, stolen calves, swollen udders, mastitis, castration, confinement, veal production, contribution to antibiotic resistance, human health problems and environmental degradation associated with dairy, it would be easier for them to find the moral courage to make the change from dairy to any of the many alternatives.</p>
<h2>Milking them for all they are worth</h2>
<p>To turn cows, who are sensitive and caring mothers, into milk machines requires regular cruelty. </p>
<p>Some of the cruellest parts of the dairy industry stem from milk and pregnancy being intertwined. Cows, like humans and other mammals, will produce milk only due to pregnancy. As soon as cows are able to bear calves, they begin a cycle of annual impregnation. This is to keep milk production high, as it would naturally slow ten months after pregnancy. Over their milk-producing lives, a cow will be milked continually, except for a two-month &quot;dry period&quot; before each calf is born. The majority of cows will be impregnated artificially, via a device wielded by a farm hand. Traditionally, and still practised in many places, cows will be impregnated on something the industry calls &quot;the rape rack&quot;: a device on which they are restrained to be mounted by a bull. Before modern methods of sexual selection, half of the calves born would be male, creating vast numbers of unwanted, less profitable calves. Today it is more common to inseminate dairy cows with semen from beef-producing breeds. This keeps milk production high, while producing offspring that can more profitably be sold to slaughter. Farmers separate calves from their mothers, usually within 12 to 24 hours of birth. This ensures the calves don&#39;t drink their mother&#39;s valuable milk and tries to minimise the development of a maternal bond between the mother and child. The pain of this separation between cow and calf is well documented in heartbreaking videos online, showing distraught cows running behind vehicles that are taking, probably yet another, calf away from them. One can hear the emotion in both mother and child as they vocalise the pain and grief of their separation.</p>
<p>Unwanted male dairy calves, sometimes called &quot;Bobby&quot; calves, are often funnelled into the veal trade. Female calves also can be destined for this fate if a farm has more than it needs to reproduce their herd, or if market conditions make it especially profitable. As dairy breeds are slowly growing and less muscular than beef breeds, it is unprofitable to raise them to adulthood, so they are slaughtered as calves for veal. Veal calves were once raised in narrow solitary crates to ensure they get minimal exercise, though this is now more commonly done in group sheds. They are given a controlled diet, often low in iron, to ensure their flesh doesn&#39;t toughen and become pink. Instead of their mother&#39;s milk, they are fed on formulas partly composed of whey protein, a waste product from cheese production. Veal calves are then slaughtered at ages ranging from just days to, more rarely, a few months old. Other calves will be slaughtered for uses such as leather or pet food and other low-grade meat. </p>
<p>If not surplus to milk production requirements, female calves will go on to join their unfortunate mothers in the cycle of suffering and death that results from life as a milk and calf production machine. They will endure having their horns removed (debudding) without anaesthetic, mastitis from over-milking, annual pregnancies with calf separation, and lameness from living with over-sized udders that are the result of generations of selective breeding to produce ever more milk. This will all end in transport to a slaughterhouse, often itself an ordeal that involves being starved and dehydrated to make slaughter cleaner. It&#39;s strange how often people will say, &quot;You don&#39;t have to kill cows to get dairy&quot;. Yet more evidence of the disconnect with the reality of animal farming systems. Every cow, beef or dairy, is destined, while still at a young age, for the horrors of slaughter. After a life of intensive calf and milk production, cows are killed when their fertility drops and their production becomes less optimal, usually between 4 and 7 years of age. Left alone, these intelligent animals would live three to five times longer, becoming matriarchs and important members of their communities.</p>
<h2>Dairy&#39;s long shadow</h2>
<p>Apart from routine animal cruelty, the dairy industry is also among the most environmentally destructive industries on our planet. </p>
<p>Dairy is a major contributor to deforestation, species extinction, air pollution, water consumption, water pollution, and greenhouse gas emissions. As outlined in the landmark Poore &amp; Nemecek (2018) study, dairy milk production uses ten times as much land, produces three times as many greenhouse gas emissions, and consumes twenty times more fresh water than equivalent plant-based milks. Dairy utilises not only the land on which cows graze that dairy uses, but also massive areas of cropland to produce their feed. The vast amounts of manure and urine produced by dairy globally run into our water and soil systems. This triggers eutrophication - with the excess of nutrients causing, among other things, algal blooms that reduce oxygen in water systems and lead to mass fish kills and dead zones. The dairy industry rarely pays the cost for their negative effects on the environment, but outsources them to governments and communities. Just grabbing a different carton from the supermarket shelf can drastically improve not only your ethical, but also your environmental footprint.</p>
<p>Many people will have heard of the Antibiotic Resistance Crisis, which is threatening to undermine one of the pillars of our modern health system. What many people don&#39;t know is that animal agriculture uses 73% of antibiotics globally, often fed as a precaution to healthy animals. Due to the mastitis caused by over-milking via machines, the dairy industry is a major user of antibiotics globally. Livestock animals do not consume all of the antibiotics they are fed; instead, the excess is washed into the environment along with their urine and manure. This environmental contamination creates a perfect evolutionary breeding ground for antibiotic-resistant &#39;superbugs&#39;, posing a severe, systemic threat to both animal and human health.</p>
<h2>Necessary?</h2>
<p>Given the negative impacts of dairy corporations on animals and the environment, how vital are they to feeding our global population? </p>
<p>Only about a third of people worldwide have the genetic mutation necessary to process dairy. Strangely, not having this mutation is often called lactose malabsorption, which makes it sound like a condition some people have, when it is actually our natural state. Humans are mammals, and mammals don&#39;t drink milk beyond early childhood; they are weaned off it by their mothers onto solid foods. This enables the child to be self-supporting and gives the mother&#39;s body a break from the costly biological function of producing milk, a phase of the reproductive cycle that consumes more of the mother&#39;s energy resources than pregnancy. When mammals exit infancy and stop consuming milk, their bodies naturally reduce the production of the enzymes needed to process lactose. </p>
<p>The majority of humans throughout history have also followed the standard mammalian path. Thousands of years ago, however, in cattle-dependent regions of Europe and Africa, genetic mutations occurred that kept lactase, the lactose-producing enzyme, on during adulthood. That mutation, called lactase persistence, is still a minority in all large populations other than those of Northern and Western European descent. Even for people with the genetic mutation, this ability tends to degrade as we age. Due to the prevalence of dairy products in many foods, especially comfort and fast foods, people will often continue consuming dairy even though they are unable to digest lactose. It is often not until people get a diagnosis or follow an exclusion diet that they figure out the cause of their digestive and other related problems. This is part of why people who give up dairy often report feeling better, even more so than those who give up other animal products. </p>
<p>Dairy is an acquired taste, a taste that will be lost over time. I can personally attest to this. I honestly thought I would not notice if I were accidentally served cow&#39;s milk in a coffee or other drink. I even said to friends, &quot;It has probably happened, and I haven&#39;t noticed&quot;. On the rare occasions I have accidentally been served dairy, I have found I notice immediately, and that it has an unpleasant taste compared to my regular plant milk. Dairy has a strange sort of musty, sour flavour, something that reminds you that cow&#39;s milk has pus in it, the levels of which are more elevated today because of the mastitis that cow&#39;s udders frequently get from milking machines. Even most dairy consumers don&#39;t seem to like that musty, sour flavour very much, as is evidenced by the highly processed, less flavourful cheeses and sugar-laden yoghurts that dominate markets. A good quality dairy alternative often tastes smoother and cleaner. Try oat milk in your coffee or beverages for a little while, and you won&#39;t want to go back.</p>
<h2>Compassionate choices</h2>
<p>Dairy is neither kind, sustainable, nor necessary. So how do we start moving beyond it?</p>
<p>Butter and cheese can be replaced by anything with some fat in it. Avocado is a common go-to for replacing them in sandwiches, burgers and salads. Depending on the dish you are preparing, there are numerous other options, such as various nut spreads, plant oils, tahini and countless variations of the amazingly versatile hummus. There are also plant-based versions of most dairy products that are getting better and more varied all the time, such as soft cashew cheeses, hard cheeses, cheddar-style slices, and even blue cheeses. Try asking for vegan mozzarella on your next pizza, and you probably won&#39;t notice much of a change at all. The most common comment my friends and family make if they try my pizza with vegan cheese is, &quot;If you hadn&#39;t told me, I wouldn&#39;t have noticed&quot;. Milk is perhaps the queen of plant-based options. There are so many types to choose from it is hard to keep up. Oat, hemp, almond, cashew, soy, rice, coconut and various blends of them are all popular, and they come in many styles such as light, creamy and specialised barista versions. You would have to be pretty determined not to find a plant-based milk that you like. Soy milk is probably the most complete nutritionally, oat milk is generally people’s favourite taste and texture for drinks, and almond milk is very popular too if you like a slightly nutty taste. Some people also like the richness of coconut milk, which can work well in sweet drinks and smoothies. For yoghurt and ice cream, here as well, there are a vast number of alternatives, with coconut being very common, but try a few and figure out which ones are to your tastes.</p>
<p>Are these alternatives all the same as the dairy products you&#39;ve acquired a taste for? With a few exceptions, the answer is usually no. They are made from different things, so you may need to acquire a taste for them, just as you once did with dairy products. It&#39;s worth doing so for all the ethical reasons already outlined, and it is a positive change you can make at a very low cost to yourself.</p>
<p>There is a massive industry trying to keep you invested in dairy.  Milk and dairy corporations are often huge, with major government support and subsidies. There is a whole deep dive you can do on the US Government Cheese programme: a vast stockpile which was partially responsible for cheese being so deeply embedded into the modern American diet. The marketing and lobbying power of the dairy industry reaches into our governments and homes globally. National Dietary guidelines are regularly published by countries, and they affect what is served in prisons, schools, hospitals and the military, and feed into the public understanding of nutrition. Groups of well-funded animal corporations and lobbying groups attend reviews on national dietary guidelines, with the dairy industry often being one of the biggest spenders amongst them. The dairy industry is also a major funder of academic research, which is vital to their interests, as studies funded by food corporations have been found to be between four and eight times more likely to have findings that align to their economic interests. </p>
<h2>Be the change</h2>
<p>Positive life changes can be hard, such as getting to bed earlier, exercising every day, keeping hydrated, being kind, and keeping the wealthy from corrupting our political systems. We often know what we should do, but find it hard to find the motivation to follow through with it. Giving up dairy, though, is very low-hanging fruit with little personal cost. Why not take this quick win for compassion and the environment? When ordering coffee, it is literally as easy as adding one word like “oat” before your order, or maybe ask your barista which plant-based milk they recommend. When shopping, just reach for a different part of the shelf where the milks are. Try a pizza with vegan cheese, pine nuts, or just some extra splashes of olive oil. A little exploration, some often small changes in habits, and you won&#39;t look back.</p>
<p>Finally, this may be heresy to many vegans, but if cheese really is that much of a sticking point, then don’t make the perfect the enemy of the good. Start somewhere else. Perhaps make perhaps the easiest change of swapping to plant milk, or maybe you only order vegan cheese only when you find it&#39;s pretty decent. Vegan cheese on pizzas is fine, and I have had many people try my vegan pizza, after which they almost always say &quot;If you didn&#39;t tell me, I wouldn&#39;t know&quot;. Eating less dairy is a good start, especially for the animals, so don&#39;t create unnecessary barriers to positive change. Like breaking other habits, sometimes it helps to minimise the habit first, have a transitory phase, so the final break seems less of a change. Millions of other people like you have made this positive change and would never look back, so you can too. Don’t think of it as giving something up, but instead as living more truly to your better self.</p>
<p>You can give up cheese; you can lean into your compassionate best self; you can be a powerful force helping to create a kinder world.</p>`;

export {
 question, short_question, alternatives, summary, discussion,
};
