
const heading = `Where would all the cows go?`;

const short_heading = `What about cows?`;

const alternatives = `What about all the farmers? What about the open landscapes of the countryside?`;

const summary = `<p>It should come as no surprise that nothing is left to chance in the big business that is intensive animal farming. Livestock breeding is strictly controlled and responds to the laws of supply and demand rather than the desires of animals or their welfare. The fewer animals people eat, the fewer animals corporations will artificially breed. It may be interesting to think about “what if we all suddenly stopped eating animals?” But, back in reality, the transition will probably continue to be gradual, and our economies will have plenty of time to adjust.</p>`;

const discussion = `<p>When people try to justify why they eat animals, the main thing the conversation generally reveals is how divorced people are from the reality of modern industrial farming. </p>
<p>Animal agriculture today bears little resemblance to the way animals were kept on farms for most of human history. People&#39;s knowledge appears to have advanced little beyond the children&#39;s book images of a cow called Daisy wearing a straw hat, the rooster on the fence greeting the sun, and the anthropomorphised smiling pig in a green field. Certainly, these are the sort of images the livestock industry adorns its products with, but it is strange that adults would believe an industrial system with billions of animals in it is still anything like Old MacDonald’s farm. Modern animal farms have thousands or even millions of a single gender and breed of animal, crowded into conditions where the only limit on cruelty is where it might interfere with profits. Chopping off tails, horns, beaks, and genitals is all routine and done without anaesthetic. Animals are taken from their mothers, fed alive into grinders, and experience other horrors that are considered just part of the business. Except for vegans who don&#39;t contribute to the system, only a tiny portion of the public seems to care about any of this. The profits of animal agriculture corporations are largely based on the near-total apathy of many animal product consumers towards the lives of animals. Exploiting animals is big business, run by vast corporations to maximise profits for their owners and investors; the slaughter of more animals is to them something only to be celebrated. In this chain of oppression of other forms of life, extending from corporate executives to end consumers, only a vanishing few people involved will ever spend a moment to bear witness to, or even think about, the lives and deaths of the animals in the system they pay for and profit from.</p>
<p>Genetics, like everything else in an industrial factory farm, is highly controlled. Breeding programmes care only about the emotional or physical pain experienced by the animals when they interfere with profit. Cruel ways of slaughtering animals are sometimes changed, not because they are cruel, but rather because in some animals the flooding of the animal&#39;s body with stress hormones is detectable in the final product. This isn&#39;t the only way that the search for profits is evident in the bodies of livestock animals. Turkeys, for instance, have had their natural form so warped by selective breeding that not only are they unable to fly, but they are also incapable of breeding naturally and must be inseminated by humans. Many farm animals, after generations of selective breeding, live with bodies that outgrow the ability of their skeleton and internal organs to support them. No animal on these farms gets to live anything like a natural lifespan, but it is perhaps a mercy for many to be slaughtered at such a young age, rather than live with the painful bodily mutations we have bred into them. Animals on factory farms do not breed naturally on their own, they only exist because we breed them. If breeding these animals becomes no longer profitable, the majority of them will disappear in a generation.</p>
<h2>Ethical transitions</h2>
<p>From a point of view of social change, it’s also not a well-thought-out question to ask what happens if industrial animal farming ends overnight, just because that’s rarely how improvements in the ethics of society happen. Ideas often spread slowly in society, usually championed by small groups of committed individuals. Often, there comes a day when a tipping point of social change occurs. Legislation banning unethical practices is finally passed, but only after much collective societal thought and planning. There may be many more vegans today than decades ago, but we are still a small minority, far from any position enabling us to widely legislate more humane farming, much less abolish animal farming. </p>
<p>Our animal product-consuming friends, often paradoxically self-proclaimed “animal-lovers” because they dote on a couple of species like cats and dogs, needn’t worry. They can give up animal products without the nightmare they fear of factory farms empty of suffering animals, or of the killing floors of the slaughterhouses not being covered in the blood of innocents. They don&#39;t need to worry about the rewilding of nature, of the native animals and plants reclaiming the pastures that were once their homes. Instead, they should be glad that the real nightmare will end, the horrific system that eating animals on an industrial scale has created in our world. We can say a long overdue goodbye to the hooks, cages, brands, barbed wire, whips, electric prods, slaughterhouses and countless other tools of animal oppression.</p>
<h2>Crisis or progress?</h2>
<p>As for what will happen to the jobs of the animal farmers, butchers, slaughterhouse workers and others in the livestock industry, that change will also happen gradually. People will transition to other work and products, just like so many changes in industries and technologies have happened in the past. New opportunities will be created because people will still need food, and will still need to eat the same amount of calories and nutrients. Those farmers and businesses who succeed will be those best able to adapt to more animal-friendly foods. This change will also be better in the long run for the people involved in the cruelties of animal farming. If fewer poor people are living psychologically traumatising lives, spending their days slaughtering animals in sheds hidden away from the rest of society, who find their work upsetting or distasteful, then that&#39;s a win for animals and humans. In the past, when society has legislated an end to cruel practices, transition plans have been put in place, including paying compensation. Nobles and owners were often compensated when serfs or slaves were freed. Although we think it strange and unjust for the state to pay out to people involved in what should always have been a criminal enterprise, it was deemed necessary for society to adapt and move forward at the time. Upton Sinclair once said it was hard to get a person to understand something if their salary depended on them not understanding it, we might expect the same about their food. Most people know on some level that factory farming is cruel, but as with other atrocities of the past, it will perhaps take some distance from it for people to comprehend its full horror.</p>
<p>As for all the open fields in the countryside, people may have grown accustomed to its current state, but it is cleared land that is more sterile and hostile to species than it once was. If we watched the trees being felled in making these cleared spaces, and saw the native animals being killed or dispersed, we might think differently. It was once said that the Roman Empire created a desolation and called it peace. Something similar could be said about clearing forests to create pasture. We should think more deeply about what we are looking at when we pass a deforested pasture full of animals surrounded by barbed wire. We rarely think about the story of who and what lived on a land in both city and country before it was cleared for humans, and how the beings who lived there were removed or dispossessed. The fields that have now been turned into monocultures of introduced species were once complex ecosystems, bustling with life forms, endless and beautiful. Ecosystems integrate millions of years of evolutionary wisdom in their subtle balance . We could perhaps begin the process of restoring them in the hope that not all that wisdom has been irrevocably lost. At least some of the workers freed from animal production industries could find meaningful work rewilding the places we have so denuded, giving the native flora and fauna a chance to return.</p>
<h2>Rewilding</h2>
<p>The benefits of rewilding pasture would be many. Livestock farming, and the crops grown to feed them, cover a huge percentage of the earth’s surface. Environmental reports from the United Nations and other authorities have long said that livestock farming is globally one of the primary causes of environmental degradation. It is a leading cause of species extinction, deforestation, water pollution, air pollution and most other environmental problems. The monopolisation of land by the high-profit livestock industry threatens not just non-humans. Much of the land of dispossessed poor and indigenous people over recent centuries has been usurped to farm high-profit livestock by privileged elites or colonisers. The already large carbon footprint of livestock farming, quoted by bodies like the UN, usually does not include the carbon reduction benefits we would all share by rewilding millions of acres of pasture and cropland currently dedicated to livestock and their feed. Other than ending our reliance on fossil fuels, there is no industry that even competes with animal agriculture in terms of negative environmental and political impacts.</p>
<p>What do barbed wire, cages, chains and other tools of confinement and oppression say about the lives of the animals who live there? What do they say about humanity? Some people have said we should call our current ecological age the Anthropocene, to acknowledge the overwhelming effect humans now have on the living systems of the world, especially since the Industrial Revolution. Humanity has collectively used its ever-growing power to selfishly diminish the home we share with all other species. Livestock farming is an exaggerated example of the ramifications of this selfishness. Factory-farmed chickens, one of the most abused animals on Earth, are now two-thirds of the mass of all birds. Humans and their livestock comprise over nine-tenths of the combined mass of all terrestrial species. Wild species are crowded into the remaining tenth, with many of them diminishing or disappearing. We often focus on the extinction of species that humans have caused, but the massive loss of members of wild species has been even more catastrophic in terms of suffering. There is no doubt humans are intelligent and have advanced organisational abilities, but on an evolutionary time scale, what have we used these traits for? To create a tyranny for all other life seems a wasteful and terrible thing to do with our potential.</p>
<h2>Transcending anthropocentrism</h2>
<p>The religions and philosophies of societies invested in animal agriculture tend to centre around human supremacy, with only the gods of our imagination being higher than humans. In an example of how self-serving human thought can be, we imagined those gods to be obsessed with the lives of humans above all other things. We see anthropocentrism flowing from our philosophies into the way we live, the things we consume and the technology we create. Our concrete and asphalt-dominated cities are deserts for wild animals, certainly most of the animals that evolved in the places our cities have replaced. Finding a way to reintegrate human civilisation into the natural world seems to be the only path forward for humanity that is not built on the oppression of everything else that lives. The positive emotions most people who spend time in nature feel tell us that if we allow nature to restore itself, we will be rewarded with happier and more beautiful lives as well.</p>
<p>A new, more harmonious self and world await once we can shake off the habits and ideas of the past to find a more equitable relationship between humanity and the other species that co-evolved with us. This is not our planet; all life has its own evolutionary paths that are not subservient to our desires, and indeed, we will flourish best together. Having the power to dominate other animals does not give us any moral right to do so. Indeed, our treatment of other animals makes evident that we need to spend more time on our collective philosophies to summon the collective maturity to responsibly wield our ever-increasing power. </p>
<p>Oppression not only damages the oppressed, but it also limits the vision and full flourishing of the oppressor. The livestock industry is the very definition of oppression; it is a symptom of our rampant myopia, and we should celebrate the gradual replacement of these cruel, unnecessary industries because it will reflect a wider ethical and intellectual progression for us all.</p>`;

export {
 heading, short_heading, alternatives, summary, discussion,
};
