// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `Where would all the cows go?`;


// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `What about all the farmers? What about the open landscapes of the countryside?`;


// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>It should come as little surprise that nothing is left to chance in intensive animal farming. Livestock breeding is strictly controlled and responds to the laws of supply and demand rather than animal desire or welfare. The fewer animals people eat, the fewer animals will be artificially bred. It may be interesting to think about “what if we just stopped eating animals?” but common sense says it would be a gradual transition giving society decades to adjust.</p>`;


// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>The things people say often reveal how divorced they are from the reality of modern industrial farming. How animals live on farms is far removed from the cow in a straw hat in the children’s book, or the anthropomorphised pig smiling in the sunshine that the livestock industry often adorns its products with. Animal farming is nothing like the storybook Old MacDonald’s; there are not 2 pigs, a goat, a cow, 3 chickens and a rooster smiling along with the farmer who knows their names. Modern animal farms have thousands or even millions of a single gender, crowded into conditions where the primary limit on cruelty is the tolerances of life and biologically dysfunctional stress. Using animals is big business, run by vast corporations to maximise profits for their owners and investors. A vanishing few in this chain of human domination extending from corporate executives to end consumers will ever spend a moment to bear witness on how the animals in the farms they pay for and profit from live.</p>


<p>Genetics like everything else in a factory farm is highly controlled. Breeding programmes care only about the lives or emotions of the animals if they interfere with profit. Turkeys for instance have had their bodies so warped by selective breeding that not only are they unable to fly but are also incapable of propagating naturally, and are artificially inseminated by hand. Many farm animals after generations of selective breeding live with bodies that outgrow the ability of their skeleton and internal organs to support them. Slaughtered when still children, it is perhaps a mercy for many to die at such a young age rather than live with the mutations we have bred into them. Perhaps luckily for these animals they only exist because we have bred them and if the industry stops breeding them they will largely disappear in a generation.</p>


<p>Of course it’s not a well-thought-through question to ask what happens if industrial animal farming ends overnight, just because that’s rarely how social change happens. People give up things gradually, and ideas spread slowly among societies. Vegans are still a small minority, far from any position enabling us to legislate less cruel farming practices much less abolish unnecessary cruelty to other species. Our dairy and meat-eating friends, often paradoxically self-proclaimed “animal-lovers” because they are nice to their pets, needn’t worry. They can give up animal products without the nightmare they fear of factory farms and slaughterhouses lying empty or of nature and wild animals reclaiming pastures. The real nightmare, of course, is the system that eating animals on an industrial scale has created in our world now, with the hook, cage, brand, barbed wire, whip, electric prod, slaughterhouse and countless other tools of animal oppression.</p>


<p>As for what will happen to the jobs of the animal farmers, butchers, slaughterhouse workers and others in the livestock industry, that positive change will happen equally gradually. People will transition to other work and products, just like so many changes for the better in industries and technologies have happened in the past. People will still need to eat the same amount of calories and nutrients, the market will adapt to whatever other foods they choose. If fewer poor people have to live psychologically traumatising lives slaughtering animals day after day in sheds hidden away from the rest of society then that's a good thing. There might even be compensation required if society legislates an end to cruel farming practices, in the same way slave owners were often compensated when slavery was abolished. Although we look at the compensations of slave owners as strange and unjust now, engaging as they did in what would now be (and should have always been) a criminal enterprise, it seemed necessary for society to move forward at the time. Most people know that factory farming is cruel, but it will perhaps take some distance from it, to not think that they personally benefit from it, before many people will be able to comprehend the full horror of it.</p>


<p>As for all the open fields in the countryside, people may have grown accustomed to its current state, but we have made a desolation and called it peace. We should think deeper about what we are looking at when we pass a deforested pasture full of animals surrounded by barbed wire. We rarely think about the story of who and what lived there before and how they were removed or dispossessed. These have been turned into monocultures of introduced species, but were once bustling ecosystems with life in endless forms most beautiful, integrating millions of years of evolutionary wisdom in their subtle balance. At least some of the workers freed from animal production industries could find meaningful work rewilding and restoring the places we have so denuded, giving the native flora and fauna a chance to return. The benefits of rewilding these places would be many. Livestock farming, and the crops grown to feed them, cover a huge percentage of the earth’s surface. The United Nations’ environmental reports have long said that livestock farming is globally one of the primary causes of species extinction, deforestation, water pollution, air pollution and most other environmental problems. This monopolisation of land threatens not just non-humans, much of the land of dispossessed poor and indigenous people has been usurped in order to farm high-profit livestock by privileged elites or colonisers. The already large carbon footprint of livestock farming quoted by bodies like the UN completely usually does not include the carbon reduction benefits we would all share by rewilding millions of acres of pasture and cropland currently dedicated to livestock and their feed.</p>


<p>What do barbed wire, cages, chains and other tools of confinement and oppression say about the lives of the animals who live there and our relationship with them? Some people have said we should call our current ecological age the Anthropocene, in order to acknowledge the dramatic effect humans now have on the living systems of the world, especially since the industrial revolution. Humanity has collectively used our ever-growing power to selfishly diminish the home we share with all other species. Our livestock are one of the most exaggerated extensions of this. Chickens are now two-thirds of the mass of all birds. Humans and their livestock comprise 96% of the mass of terrestrial species, with all wild species crowded into the remaining 4% and many of them diminishing or disappearing. Humans have utilised our intelligence and organisational abilities to create a tyranny for all other life.</p>


<p>The religions and philosophies of developed societies centre around human supremacy, with only the gods of our imagination being higher, and even the gods we have created are apparently obsessed with us. We see anthropocentrism reflected in the way we live, the things we consume and the technology we create. Our concrete and asphalt dominated cities are deserts for most native animals. Finding a way to reintegrate human civilisation into the natural world seems to be the only path forward for humanity that is not built on the oppression of everything else that lives. The positive effects of spending time in nature for human well-being tells us if we allow nature to restore itself we will also have more beautiful and fulfilling lives as well.</p>


<p>A new world awaits when more of us shake off the habits and ideas of the past to imagine a more equitable relationship between us and the other species who share our world. All life has its own evolutionary paths that are not subservient to human ones and indeed we will flourish best together. Having the power to control the lives of other animals does not give us any moral right to do so. Indeed it is evident we need to spend more time on our collective philosophies in order to learn how to summon the collective maturity to responsibly wield our ever increasing power. Oppression not only damages the oppressed, but it limits the vision and full flourishing of the oppressor. The livestock industry is a symptom of our myopia, and we should celebrate its gradual replacement because it will reflect a wider ethical and intellectual progression for our species.</p>
`;


export {
 heading, alternatives, short_answer, long_answer,
};