// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `Where would all the cows go?`;

// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `What about all the farmers? What about all the nice open fields in the countryside?`;

// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>It should come as little surprise that intensive livestock farming is intensively controlled. Livestock breeding is highly artificial and responds to the laws of supply and demand. If people stop eating animals, farmers would breed fewer of them. It may be interesting to think about “what if we just stopped eating animals?” but this is unfortunately unlikely to happen, it is more likely to be a gradual transition with plenty of opportunity for society to adjust.</p>`;

// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>Sometimes people say things that make you realise how divorced from the reality of modern industrial farming most people are. Breeding animals is big business, strictly controlled by farmers, governments and corporations to maximise profits. Insemination is highly artificial, bloodlines and genetics are completely controlled. Some animals like turkeys have had their bodies so warped by selective breeding they are no longer capable of propagating naturally. Many farm animals live with a body that outgrows the ability of their skeleton and internal organs to support them, it is perhaps a mercy for many when we slaughter them at such a young age but be better for them not to be bred to mostly suffer. If we are worried about being overrun by freed farm animals, we need to stop paying to bring them into the world.</p>
<p>Of course it’s not a well-thought-through question as it is unlikely that a change to a vegan world will happen overnight. People give up things gradually, ideas often spread slowly among societies and vegans aren’t near a position enabling us to legislate the end of cruelty in farming tomorrow. Our dairy and meat-eating, often paradoxically self-proclaimed “animal-loving”, friends needn’t worry. They can become vegans without losing sleep over the thought of creatures wandering free to live life according to their own desires. The real nightmare surrounds the hook, cage, brand, barbed wire, whip, electric prod, slaughterhouse and other tools of animal oppression.</p>
<p>As for what will happen to the jobs of the current farmers, butchers, slaughterhouse workers and others in the livestock industry, some of the same applies. The change will happen gradually. People will transition to other work and products, just like so many changes for the better in industries and technologies have happened in the past. People still need to eat, the market will adapt to whatever other things they choose, and as is often the case there may be some transitional support required. Slave owners were often compensated when slavery was abolished, we look at that as unjust now but it was perhaps necessary to move forward in the society of its time. If fewer people are needed to grow our food or live unpleasant lives killing animals day after day in sheds hidden from the rest of society, then that's probably a good thing. More people can be freed for the many other functions that could improve our society.</p>
<p>As for all the open fields in the countryside, people may have grown accustomed to its current state, but we have made a desolation and called it peace. We rarely think about the story of who and what lived there before and how they were removed or dispossessed. These were productive ecosystems, not monocultures but bustling with life in endless forms, integrating millions of years of evolutionary wisdom in their subtle balance. At least some of the workers freed from animal production industries could find meaningful work rewilding and restoring the places we have so denuded, giving the native flora and fauna a chance to return. The benefits of rewilding these places would be many. Livestock farming, and the crops grown to feed them, cover a huge percentage of the earth’s surface. This is why the UN and other agencies have pointed out that livestock farming is one of the primary causes of species extinction, deforestation, water pollution, air pollution and most other environmental problems. This monopolisation of the land threatens not just non-humans, much of the land of dispossessed poor and indigenous people was taken to farm high-profit livestock by privileged elites or colonisers. The already large carbon footprint of livestock farming quoted by bodies like the UN completely does not include the positive carbon benefits of restoring millions of acres of natural habitat.</p>
<p>The countryside of cleared fields surrounded by fences and barbed wire needs to be rethought. What does that barbed wire say about the lives of the animals who live there and our relationship with them? We are living through the Anthropocene, a term that acknowledges the effect humans and the livestock we breed have on the living systems of the world. We have abused our ever-growing power to diminish the natural world we share. Chickens alone are two-thirds of the mass of all species of birds. Humans and their livestock comprise 96% of the mass of terrestrial species, with all wild species crowded into the remaining 4% and many of them diminishing or disappearing. We have utilised our intelligence and organisational abilities to create a tyranny.</p>
<p>Our religions and philosophies have centred around human supremacy in the world, and we see this reflected in the way we live, the things we consume and the technology we create. Removing our foot from the neck of nature is not about changing the world so much as it is about helping it restore itself to its recent past, allowing it to breathe. Finding a way to reintegrate human civilisation into the natural world seems to be the only path forward for humanity that is not built on the oppression of everything else that lives. Everything we know about the positive effects of spending time in nature for human well-being also tells us that as nature restores itself we will have a more beautiful and fulfilling life as well.</p>
<p>A new world awaits if we can shake off the habits and ideas of the past to imagine a more equitable relationship between us and the other species who share our world. We should respect that all life has its own evolutionary paths separate from ours. We should stop believing that simply having the power to control the lives of other animals gives us any right to do so, especially when it is so evident we do not have the collective maturity to responsibly wield that power. The livestock industry is a symptom of our myopia, and we should only celebrate its gradual replacement because it will reflect a wider ethical progression for our species.</p>
`;

export {
  heading, alternatives, short_answer, long_answer,
};
