
const heading = `Why do you eat things that look like meat?`;

const alternatives = `Thinking that every vegan alternative is made of tofu. Thinking all vegan alternatives have unnatural ingredients.`;

const short_answer = `<p>If you are offended by someone happily eating a veggie burger or sausage, and not by billions of animals suffering in slaughterhouses and factory farms, perhaps you need to reconsider your ethical framework. Vegans are generally more concerned with the ethics, not the aesthetics, of what we eat. If people are bothered by food that hasn&#39;t involved the factory farm and slaughterhouse, then it is those people, not the vegans, who need to change.</p>`;

const long_answer = `<p>If carnists are so offended by vegans eating veggie burgers and sausages, this begs the question: why aren&#39;t meat eaters eating things resembling animal parts? A rissole, a burger pattie, a sausage, a bolognese, even a steak, none of these things exist in the form people eat them in nature. If animal products are so naturally delicious and appealing, why aren&#39;t there restaurants everywhere giving it to carnists the straight flesh? Raw severed pig&#39;s leg, anyone? Maybe just leave a live rabbit on the table for the diners to kill and process themselves, especially without tools. Instead, animal flesh is sold after removing the fur, skin, feathers, scales, bones, organs, head, tail, hooves, draining most of the blood and then shaping, spicing, marinating, saucing, texturing and burning. We really need to ask why carnists won&#39;t eat things resembling animals?</p>
<h2>Our long history of alternatives</h2>
<p>We should start with a history lesson. There have been vegetarian sausages for a long time, certainly since the 19th century. During the First World War, what were called &quot;peace sausages&quot; were created due to rationing and meat shortages. Though primarily made of soya, they would sometimes contain traces of meat. Vegetarian burgers have a much longer history, with a 14th-century recipe book talking about how to make Broadbean patties. Tofu is at least over 2000 years old, and soy milk was being produced as a byproduct not long after. Seitan, one of the most popular meat substitutes made of wheat gluten, was mentioned in China in the 6th century. In the early 18th century, it featured in an Italian cookbook. It was commercially available in the USA in the late 19th century. Centuries ago, China was the originator of most mock products, useful as they were for Buddhists looking for vegetarian meals. Mock meats and plant milks are nothing new, but there do suddenly seem to be people very worked up about them. Conservative politicians aligned with animal product producers have been alarmed at the rise in consumption of plant foods, and so have tried to ban the use of terms like milk, sausage, burger, yoghurt and so on. In some cases, like Canada and South Africa, they have been successful. In Turkey, they have even banned the production of vegan cheese alternatives. Why this is so triggering, and why a movement against these products emerged in the early 21st century, is an interesting question involving commercial interests, conformity, masculinity, resisting modernity, and culture wars.</p>
<h2>Reclaiming words</h2>
<p>Interestingly, the word meat didn’t originally mean animal flesh; originally, it just meant food, and then more specifically, substantial, hearty food. It wasn&#39;t until the 19th century that it completely replaced the wider usage of the term, coincident with an increase in the consumption of animal products. Before refrigeration and factory farming, consuming animal products in the quantities now common was unrealisable for the average person, especially those living in cities. This is evident in most cultural cuisines, which were historically primarily plant-based. The diets of most countries only became so animal product-heavy relatively recently, so much so that the definition of meat changed to mean only animal flesh.</p>
<p>Back to animal products looking like animal products, carnists seem unreasonably precious about terms here. We don&#39;t want to spoil any delusions, but most fish don&#39;t have fingers, and buffalo don’t have wings, though we don&#39;t see anyone get upset about these terms. Cheese, butter, sausages, milk and burgers. Most animal products go through production processes that alter them significantly from their natural look and state. What humans seem to like is cooking, combining, mixing, shaping, flavouring, texturing, and cleverly creating different culinary experiences. These processes are the same used with plant-based foods. Tofu is an excellent example of this: some people try tofu raw and find it unpalatable. You could say the same about most starchy root vegetables like potatoes, a foundational part of the global diet. You need to do some preparation for the deliciousness of potatoes to reveal itself. I know a few hardcore people who like to eat raw tofu, but then I once knew someone who ate raw brown onions like apples, so there&#39;s no accounting for taste. Everyone else I know who enjoys tofu adds some salt and pepper, or a marinade, cooking it in various ways, adding maybe a dash of chilli or soy sauce, then some veggies and carbs on the side, and suddenly you have a dish that provides plenty of nutrition and flavour. Tofu does come in a wide variety of textures, so it takes a little experimentation with the softer and firmer varieties for the right dish. If using it as an alternative protein, try the firmer varieties.</p>
<h2>Decentering meat</h2>
<p>People often mentally focus on animal products when they are only part of what they eat. I read a news story about a group of men who went on a camping trip together, and they said it had been a meat fest. They had collectively consumed something like 50kg of meat on the trip. Later in the story, it was noted that they had eaten more than 50kg of vegetables on the trip,  no doubt with plenty of bread and other plant-based foods. They didn&#39;t describe their male bonding session as a vegetable fest, even though it would have been more accurate. Take your standard burger, that carnists with nothing better to do complain vegans need to come up with some alternative name for. Like many other meals, the flesh in most burgers is just part of the total nutrition and calories. Take one of the most commonly eaten burgers in the world, the communion wafer of modern consumerism, the Big Mac, three-fifths of it by weight are non-animal ingredients: bread, oils, sauces, lettuce, onion, pickle, and so on. Generally, if people are just eating a burger, called a rissole when I grew up, the patty is flavoured with herbs and spices, vegetables are then added such as onions and capsicum, and then it is finished with flour or breadcrumbs. All burgers are seasoned, then grilled in oil, to further change the texture and flavour. With most fast food, the meat is only a part of the final product, or it is so heavily processed and flavoured it barely resembles or tastes like animal flesh would have naturally. If vegans replace the meat in any of these dishes with some plant-based protein source, mainly for mouth feel and texture rather than flavour, we still get a pretty similar end experience. Why people get offended by this, and how they can find it something more worthy of getting upset about than slaughterhouses and factory farms, is hard to fathom.</p>
<p>What people who go vegan often realise is that it wasn&#39;t the taste of meat that added much to food, it was their practical use as an ingredient in a meal, especially their texture, fat content and protein. I find texture particularly important; a burger without a dense patty is a little too easy to chew through. Humanity has spent centuries coming up with different recipes, like the burger, and vegans see no need to ignore this culinary history when we can continue mining it for pleasure. Everything an animal product brings to a meal can be replaced with other things that have similar properties. If we swap a few ingredients and then add the same spices and flavours and cook it in a similar way, we end up with something that ticks the same pleasure boxes for us. How well do plant-based alternatives mimic animal products? Some of the commercial products can be almost uncomfortably similar, but most of the time, when cooking at home, they are not exactly the same, but pleasurable in a related but different way. If you&#39;ve ever met people who argued passionately about which of two similar products is better, say Coke or Pepsi, Android or Apple, Vegemite or Marmite, you realise some of our preferences are pretty arbitrary and often inconsequential. After you&#39;ve had a sufficient break from animal products, your tastes and expectations will adjust; personally, I don&#39;t compare things anymore because it&#39;s been decades since I ate animal products. You couldn&#39;t look into a busy vegan restaurant and know it was any different to any other restaurant, as the carnists who accidentally walk into them sometimes find out. You will see people ordering and enjoying food, talking happily with friends, full of the same joy of food and life.</p>
<h2>Beyond meat</h2>
<p>When it comes to replacing animal protein, we have a wide array beyond the mighty tofu. Beans and lentils are the easiest, cheapest and often healthiest drop-in replacements, but there are also nuts, seeds, grains, mushrooms, seitan, soy derivatives and other alternatives from the wide and diverse plant kingdom. There is a range of commercially made products that are increasing in quantity and quality. They are designed to be like-for-like replacements for animal products in a meal and are especially helpful for people making the transition. If someone wants to start having plant-based meals a few times a week without much fuss, what could be easier than swapping in some plant-based chicken strips into their usual stir fry or tacos, or some veggie mince into their bolognese, chilli or shepherd&#39;s pie. These vegan alternatives are getting better and more varied all the time as veganism grows and becomes more commercially profitable. People often prejudge plant-based food as boring, but blind studies show that people like the taste of plant-based alternatives more than they expect. Eating food without animal products at the centre is more of a mental shift for many people than any other aspect of the change. As we all did for our current diet, perhaps unconsciously at our family kitchen table, we need to learn a way of eating. To eat a vegan diet, we need a little relearning, finding what foods we like and don’t like from the ever-increasing number of vegan options out there. We need to experiment with different plant-based recipes and options. Most of the work is done if we can figure out a handful of staple dishes that form the core of most people&#39;s diets.</p>
<p>Above all, people asking why vegans enjoy a veggie sausage are missing the point. Nobody goes vegan because they object to the texture, shape or flavour of animal products. People mostly go vegan because they object to the violence and oppression inherent in animal products, to boycott a system they see as cruel, environmentally damaging and unnecessary. A lot of vegans do avoid products resembling animal foods because they have uncomfortable connotations for them, and that is fine. Other vegans are happy eating anything so long as it isn&#39;t contributing to factory farming. Personally, I enjoy these products and see them as clear evidence of how little we need to give up to end factory farming and live more compassionately.</p>
<p>There are many things we could get offended by in the world, but we need to have some sense of proportion about what actually matters. Finally, to repeat the point I made above, if people are offended by others happily eating veggie sausages, and not by billions of animals suffering in slaughterhouses and factory farms, they need to reconsider their ethical framework.</p>`;

export {
 heading, alternatives, short_answer, long_answer,
};
