// This appears under the pictures on the square, and at the top of its
// Format: Text.
// individual page.
// Format: text.
const heading = 'Hitler was vegetarian';


// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: text.
const alternatives = `Pol Pot, Charles Manson, anyone who clearly was a terrible human being`;


// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>People should be more informed about and respectful towards the atrocities of history than to use them for their own ideological purposes. It is not only illogical but perversely ironic to try to morally equate those involved in the mass killing of humans with those trying to stop the mass killing of non-humans. Surveys show that people who care about animal rights are more, not less likely than the rest of the population to be concerned about human rights. Veganism is about universal compassion, one which requires that we consider the interests of all sentient beings and was never intended to exclude humans.</p>`;


// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>Godwin’s law arose in the early days of Internet discussion, but it has come to be applied more broadly. The law states that as a discussion or debate grows longer, the probability of someone making a comparison involving the Nazis or Hitler approaches a certainty. Therefore someone trying to equate people who want to be kinder to animals with some of history’s worst people was perhaps inevitable. Vegans and vegetarians are seen as making a choice to care about animals and not people. Surveys repeatedly show, however, that caring about animals and humans is not a dichotomy, but a mutually compatible expression of a wider compassion. We should also tread carefully in making comparisons with one historical injustice and another, with one form of cruelty and another. Whilst there may be some important ways in which they are similar, there are no doubt others in which they are not. We will try to tread carefully with that in mind.</p>
   
<p>Hitler, Pol Pot and Charles Manson never claimed to be vegan or even vegetarian, but people repeatedly want to claim that they were, so it is something that needs to be addressed. We should start by acknowledging that evil people have eaten vegetables, some maybe even a lot of vegetables. It is also statistically certain that some of the many millions of people over thousands of years who have been or tried vegetarianism will have been terrible people. That a plant-based diet or philosophy  causes people to be evil is, however, seems less plausible.</p>


<p>Tolstoy said that vegetarianism shows that a person's pursuit of moral perfection is sincere. This probably needs an update to include “veganism”, but while it sounds nice, not everyone gives up eating meat for the pursuit of ethics. Health, religion, spirituality, culture, digestion issues, allergies and impressing a hot vegan are all common. If a person abstains from eating meat for reasons other than ethics, it probably doesn’t tell us too much more about them than other dietary choices. Some people have claimed that eating meat changes our nature, like the violence we are consuming inhabits our soul in some way. It’s possible there are hormonal or other chemical things going on that we consume in animal flesh that make us more prone to violence, and that stopping eating meat would make us more peaceful but we’d need good evidence before we would believe this. It’s also possible the opposite is true; some of the animals we consume have gentle natures which is part of the reason they make good targets for oppression, and perhaps we become more docile like them as we consume them. For now though, we don’t seem to be able to confidently assign good or bad behaviour to this aspect of our diet. People are also complex and most of us are ethical in some areas but have moral blind spots in others. We need to know more about someone to say if they are overall a good person than what they had for dinner. Brahmin families in India have abstained from meat for many centuries, but it's doubtful every single person they produced was some sort of saintly figure. Vegetarians and vegans are regular people, often flawed, trying to figure out this life as they go along like everyone else.</p>


<p>Now let's add to the millions of words humanity has wasted talking about the wretched Hitler. He definitely ate meat regularly until he was almost 50, by which time he had taken over Germany and was having his political enemies, followed by Jews, Roma, people with disabilities and others put to death. It was 1942, well into the war and almost 10 years after the concentration camps were opened, before he ever seemed to say anything remotely vegetarian. So the claim is on shaky ground straight away, if we think his diet was in any way related to his crimes, it is not his late vegetarianism we should be looking at but his 50 years of meat eating before it.</p>


<p>
Hitler had long-term stomach problems, and some say doctors put him on a mostly vegetarian diet around 1937, though Herman Hess said he made exceptions for things like liver dumplings. Even later on, people apparently unafraid of the consequences of crossing Hitler snuck meat into his food right to his end, and if he noticed he would complain about it hurting his stomach. His chef claimed she used animal broth in cooking for him and his dietitian claims to have snuck bone marrow into his food. So how much he was actually vegetarian is hard to tell, from these anecdotes it could be said he never was. Hitler did show some concern for animals, liked dogs and the Nazis did enact laws against animal cruelty, but if people were just pure evil history would be a lot simpler. The Nazis also had social programmes and helped the poor, so although the Nazis as a collective were incomprehensibly vile, not every single thing they did was. As the saying goes, even a stopped clock can be right twice a day.</p>


<p>On to Pol Pot and his murderous regime. This was relatively recent, the people who cooked for him are still alive, and they say he ate all sorts of things, fish, cobra, boar etc. An official who knew him seemed to say he was a vegetarian, but who knows what they were basing that on? As an aside, we must understand that many people get confused about what the word vegetarian means, especially in the past. A relevant passage talking about Hitler’s diet from the New York Times in 1937 says “It is well known that Hitler is a vegetarian” which they then follow with “he occasionally relishes a slice of ham and relieves the tediousness of his diet with such delicacies as caviar”. Studies show that even today many people, especially older people, get confused when asked to define vegan or vegetarian. Diet surveys have had to be amended because of the poor understanding of vegetarian and vegan. For instance, after surveys ask people if they are vegetarian or vegan, they then ask "When was the last time you ate chicken?" to try to make sure people mean what we usually ascribe to the word. What does someone in 1940s Germany mean when they say vegetarian, or 1970s Cambodia? Pol Pot doesn’t seem to have been vegetarian, so another blight on the meat eaters of the world perhaps.</p>


<p>Finally Charles Manson, the Internet has failed me here. A lot of slightly unhinged websites gleefully assert he was and a couple of better-hinged ones as well, though none of them provides any evidence. Still, although he hated hippies and thought they were weak, he dressed like one so maybe he decided to eat like one. Will mark this one as inconclusive.</p>


<p>So what motivates the repetition of this claim about Hitler etc to people who don't eat meat? Some people seem to have a need to pre-emptively attack a vegan because they imagine being judged; almost like there is a conversation already in their head about the ethics of our treatment of animals that a vegan unknowingly steps into. People don’t want to be looked down upon, they want status, including moral status, but surveys show that many meat eaters are uncomfortable about the treatment of animals in the food system, but they are stuck in the habit of how they eat and don’t want to change. So they are left in an uncomfortable state, and this is what's called cognitive dissonance. To avoid change without having a troubled conscience they need to find intellectual justifications for any of their behaviours that they feel on some level to be morally questionable. So you get "Hitler was a bad person, Hitler was a vegetarian, therefore vegetarian and vegans are bad people"; Aristotle wouldn't have thought much of this syllogism but any logic, even poor logic will often do for a person seeking an exit from a moral quandary. Judging others is often a way to redirect our inner voice that might instead start questioning ourselves.</p>


<p>Adding to poor logic we also have poor statistics; you can't make widespread inferences about a group of people from cherry-picked examples. Even if Hitler and Pol Pot actually were ethical vegetarians, what about Mao Tse Tung, Joseph Stalin, Talat Pasha, Suharto, Saddam Hussein, Atilla the Hun, Genghis Khan, Nero, Caligula, King Leopold, Idi Amin, Vlad the Impaler and of course the vast, vast majority of Nazis who were meat-eaters. But you don’t find vegans saying to carnists “Oh you eat meat, well Donald Trump was a meat eater”. Even though it may be true, it doesn’t tell us much about the character of the person we are talking to. Many vegans didn’t start life as vegans, that they too ate meat, not because they were bad people but because that is what they were taught, and they just hadn’t really considered the lives of other animals enough, or didn’t have the tools and mindset to do something about it.</p>


<p>Given the scale of animal suffering at human hands, the billions huddled in factory farms, their bodies altered to be production machines and the many wild species of the world in retreat or facing extinction, how can it be argued this is not a moral spot on which we need to shine some light? People should think carefully before engaging in knee-jerk reactions against people arguing for a better relationship between humans and non-humans. Even if you think they are wrong, is having compassion, maybe even too much compassion for other species more terrible than the problem it trying to bring attention to? This is not to say that vegans who lack empathy for people should get a free pass to be rude or inconsiderate. Veganism when properly understood is about compassion and consideration for all that can suffer, and this should include humans.</p>


<p>Any ethical outlook that considers humans but not animals, or animals but not humans, or some subset of humans or animals is incomplete. All sentient beings deserve consideration of their interests at least according to their level of sentience. An ethically and intellectually consistent life should have at its core compassion for all beings who can suffer, for all earthlings who share these evolutionary moments of existence together. Veganism is not a diet, it is a philosophy of universal compassion.</p>
`;


export {
 heading, alternatives, short_answer, long_answer,
};