
const heading = `What about backyard chickens?`;

const alternatives = `What if animals were farmed humanely?`;

const short_answer = `<p>Chickens, perhaps even more than any other farmed animal, have been abusively bred to be production machines. The breeds of hens in our farming systems have been selectively manipulated to lay hundreds of eggs yearly, ten times more and larger eggs than their wild forebears. This is only one facet of a torturous regime that is inconsistent with health and quality of life. Life in a backyard would almost always be better than a factory farm, but hens cannot escape that their bodies have been bred to suffer. If you care at all about the suffering of these friendly, inquisitive creatures, the best policy is to eat something else.</p>`;

const long_answer = `<p>The industrial factory farm is one of the cruellest creations of humankind. It&#39;s not meat-eating itself, but the sheer quantity of meat people consume, and the relentless push to make it cheaper, that has led inevitably to the factory farm. There is a perverse cycle: creating a more industrial system that sacrifices animal welfare leads to cheaper animal products, and cheaper animal products lead to people consuming more of them, feeding and intensifying the industrial system. There is much talk about historical human progress, and while there are many rising indicators of human ethics and well-being, for animals, a different story is unfolding. There have never been more animals living in factory farms, and the conditions of their lives have trended towards ever more confinement, more intensive genetic meddling, earlier slaughter, and less autonomy to pursue their natural desires.</p>
<h2>Economics over ethics</h2>
<p>A widely viewed debate about the ethics of eating animals started with the side defending the eating of animals with a statement which went something like this, &quot;We don&#39;t support or want to defend the factory farm&quot;. To avoid talking about factory farming in discussing the real-world ethics of eating animals is to reduce the practical consequences of the discussion almost to irrelevance. In the United States, the percentage of animals raised on &quot;humane&quot; farms is below 1%. For pigs, chickens, ducks, and increasingly cattle, the number of individuals on farms leading anything like a decent, natural life is a rounding error. </p>
<p>It is economics, not ethics, that governs the life of farm animals. The inescapable consequence of billions of people wanting to eat cheap meat every day is that for each of these people, a community of animals has to endure life in factory farms before their, literally, premature slaughter. Industrialised animal agriculture and the universal meat-heavy diet are modern creations wholly dependent upon each other. To abolish the worst aspects of factory farming, to meaningfully reduce the suffering and vast environmental footprint they cause, animal product consumption would, at a minimum, need to be scaled back to pre-industrial levels.</p>
<p>Some remarkable surveys in developed nations have shown wide support, often around half of the population, for banning slaughterhouses and factory farms. People will say they want animals to be treated better, and even say they want to eat less animal products, though usually for their health, but people also don’t like change or paying more for things. So in the place of consequential action, they fantasise about impractical fixes that they aren&#39;t morally serious about enough to think through fully, much less implement. People talk about more humane farms as if they could be a “drop-in” alternative for factory farms, providing a win-win outcome of humane meat for relatively similar prices. Neither part of this win-win dream is true. The best these farms are currently providing is slightly less cruel meat at prices much higher than standard factory-farmed products. For decades, factory farming corporations have been optimising and refining a system built on the subjugation of every animal interest to profit. Anything resembling a traditional farming approach will never be able to compete with the scale and efficiency of these huge international conglomerates built to churn out animal parts and secretions.</p>
<h2>Hypocrisy</h2>
<p>Even among the rare animal product-consuming people who think much about humane farming, very few of them are even vaguely consistent in what they buy. It is actually a strange thing to be vegan, and have so many people ask you questions like &quot;What about if we treated animals better?&quot;, but when you ask how often they buy more humane alternatives, the answer is usually a blank stare. This has actually improved slightly since free-range eggs and &quot;certified&quot; products have become more common. They do often have some significant improvements in welfare over alternatives, but they are also limited in their scope purely by economics. Why people who eat meat regularly bring up the discussion of humane farming, which they don’t seem to want to pay very much for or go to any effort to make happen, remains a mystery. It&#39;s like their fantasies about humane animal farming creep into the real world just enough to absolve their conscience about what is actually going on. There are many nice fantasies we can have, but surely it is what we do and pay for to happen in the real world, where animals daily suffer and die for our food, that counts morally.</p>
<p>Backyard farming has an emotional appeal, as it tries to replicate the stories we liked to read as children about how animals are farmed. Mother hens clucking happily with their chicks under their wings, a rooster on a fence crowing to greet the sunrise, the happy piglet on some grass, the smiling cow with a flower in its mouth and calf by her side. These fairy tales are often replicated on the outside of the packaging of animal products. Inside the packaging, however, is the reality of a dismembered animal that experienced many cruelties and had an unnaturally short life, before it was transported to face the horrors of a slaughterhouse. Many of them have never known consistent family or relationships, have never been allowed to express their natural behaviours, or have seen the sun except perhaps when crammed together as they are being transported to their death. Pigs, cows, roosters, large fish- there are very few animals that can fit into the backyard farmer ideal, but then backyard farming is more about bucolic fantasies than any serious solution to the widespread suffering of farm animals.</p>
<h2>Out of sight, out of mind</h2>
<p>Back to the poor chicken, perhaps the most widely abused animal in the world. If you ever wonder about the scale of factory farming, think about the fact that two-thirds of the total bird mass in the world is composed of chickens in factory farms. If you are thinking of rehoming an animal from a factory farm that would otherwise go to slaughter, whilst a noble idea, it comes with various health and often mental issues for the birds. Corporations with profit, not hen welfare in mind, have bred the modern factory-farmed hen. Wild chickens lay one or two dozen eggs, split into two clutches each year. The modern factory-farmed chicken has been bred to lay 10-15 times this amount, averaging an egg every day. The eggs they lay have also become significantly larger. This takes a terrible toll on the hen&#39;s small bodies, leaching calcium and other vital nutrients. Animal sanctuaries that take in hens from factory farms often give the hens hormones to slow down their egg production and give their bodies a chance to heal, though this isn’t a healthy long-term solution either. Chickens can live for up to 20 years, but egg-laying factory-farmed chickens are killed when they are younger than two years old because, in industry jargon reminiscent of machines, &quot;their production falls rapidly&quot;. In other words, their reproductive systems and bodies are spent, and they are slaughtered so some unfortunate younger hen can take their place. </p>
<p>The brothers of these egg-laying hens don&#39;t escape a cruel fate either. They are worthless to the industry, so they are immediately killed. The chicks are killed en masse, generally by being fed through a grinder (called maceration or shredding) while still alive or by suffocating/gassing. Note, these horrific methods are considered the “more humane” ways of killing male chicks, and are recommended in Australia by the RSPCA. The Royal Society for the Protection of Animals is the primary body certifying welfare standards for animal agriculture in Australia. They certify 90% of chicken products sold under the brands of our major supermarkets. Allowing fast-growing breeds and grinding male chicks alive are just two of the cruelties that they allow to bear their stamp of approval. The Royal at the start of their name is perhaps the first hint as to how progressive the RSCPA are with respect to farmed animals, but more revealing is that their certification logo has a dog/cat paw in the middle of it. They perpetuate the older standard of animal welfare societies, which were mainly concerned with the treatment of cats, dogs and other pets we share our daily lives with. This attitude, the very definition of speciesism, allows other animals to be consigned to live in factory farms. I&#39;ve seen footage of the conditions inside an RSPCA-certified piggery, and if anyone were to keep their pets in such conditions, the RSPCA would call for their prosecution. Animal welfare standards often have specific exceptions for farm animals, because apparently, cruelty is fine when it keeps meat cheap and corporate profits flowing. Consumers, in turn, enjoy the cheap animal products and ask few questions, the answers to which they don&#39;t want to hear anyway, because they might trouble their conscience.</p>
<p>In backyard farming, the problem of too many male birds doesn&#39;t go away. Roosters aren&#39;t as placid or useful as hens; they are often noisy, fight and of course don’t lay eggs. Roosters can also live up to twenty years, but are instead mostly slaughtered in backyard farming at 3 to 4 months, before they start to mature. The hens are also generally slaughtered by serious backyard farmers as their reproductive systems start to slow down. Backyard farming may alleviate the intense confinement and cages, but it still involves slaughter and often much of the physical suffering.</p>
<p>Factory farms and slaughterhouses are terrible places, and that is even with some oversight by the government and the occasional activist breaking in and documenting conditions in them. The unregulated, unseen nature of backyard farming might, on average, be better, but it can also go more awry. Amateurs keeping chickens purely for economic and production reasons risk having chickens suffering more painful deaths, neglect of their welfare, untreated diseases, lower standards of care, less protection from predators, and hidden abuse. Paying a vet to visit a sick chicken makes little sense if you have the animal for partly economic reasons. Suffering does exist on a scale, however, so despite possible wider variations, raising backyard chickens should mean an average improvement in hen welfare.</p>
<h2>Bucolic fantasies</h2>
<p>As a solution to the vast industrial system of factory farming, how scalable is backyard farming?  In Australia, the average consumer pays for twenty-five to thirty broiler chickens a year to be raised and slaughtered on their behalf. A small family of four or five people might need to slaughter around 120 chickens a year to maintain the average diet. This would obviously mean a larger flock than this to maintain breeding numbers, and some for eggs and so on. Chickens are less than half the meat Australians eat, so we would need to add a variety of other beings to this hypothetical backyard as well, ponds for fish, stables, milking facilities and so on. A nuclear family would need to maintain a reasonably sized farm to sustain anything like the current levels of animal product consumption. How is this going to be done in the small suburban yards and apartments that today&#39;s increasingly urbanised and concentrated populations live in? This is all part of the reason most humans historically didn&#39;t eat as much meat as we do now: it simply wasn&#39;t possible before refrigeration and factory farms. If you want to argue for maintaining the modern animal-product-heavy diet, then you are arguing for maintaining factory farms.</p>
<p>Perhaps technology can provide a way out of this ethical dilemma and enable us to go on as we are without having to change? Cell-cultured meat, precision fermentation, and molecular farming: there are currently a handful of technologies that could hypothetically remove animals from factory farms and allow people to continue eating animals at current levels. None of these is yet proven at any scale, and until this happens, we will not know if they can compete on price with the industrialised animal agriculture system. We also have little knowledge of whether the products they will produce will be comparable to current products in texture or considered acceptable to consumers. The resistance many people and countries have had to genetically modified foods is perhaps an example of the resistance animal proteins produced by unfamiliar technologies could, and probably will, create. </p>
<h2>Ethical simplicity</h2>
<p>People who aren&#39;t vegan often get the idea in their head that being vegan is hard or complex, but this is just unfamiliarity and habit speaking. As a long-term vegan, I generally find it simple: did the food come from a plant? Yes, then om nom nom! To be an ethical animal-product consumer seems harder. The primary thing you need to know is not what to eat but how the thing you are eating was produced. If you eat animal products in packaged food, go to restaurants and cafes, and eat with friends, family and colleagues, it seems there would need to be a lot of research and questions raised about how the animals were treated. I can imagine long discussions with waiters and other people who provide food to you. Backyard farming isn&#39;t going to change much of what happens when you purchase animal products outside of your house. If you want to live in a more ethically consistent manner, the simpler and more effective path would just be to go vegan. When talking about ethics, these sorts of practicalities are relevant but not the core of the story. Taking a sentient being&#39;s freedom away, using its body for profit and production, disrupting their lives and families, and prematurely killing them, has to be oppressive. </p>
<p>Habit can blind us to our agency, that every day we are making powerful choices about other sentient lives. Through our daily consumption choices, at restaurants and supermarkets, we directly affect animals, whether they experience more or less pain. We affect the lives of others for better or worse, even if we aren’t aware of it, because we never see or interact with them. Veganism is part of engaging with this wider ethical reality, of a hope that humans can transcend being a narcissistic and oppressive species.</p>
<p>We can do better than turning our backyards into more places to oppress and slaughter animals. Paying to outsource oppression and slaughter, however, as most people currently do, is even less ethically acceptable. Luckily, we have a simple choice we can make to escape this ethical quandary. By joining the growing millions living happy and healthy vegan lives, we can be part of a movement showing the way to a brighter shared future between human and non-human beings.</p>`;

export {
 heading, alternatives, short_answer, long_answer,
};
