// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `What about backyard chickens?`;

// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `What if animals were farmed humanely? My uncle has a farm...`;

// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>On average a chicken in the backyard of a family is going to have a better life than one in a factory farm, almost certainly if the factory farm uses intensive confinement. Like other factory-farmed animals though, they have been bred as production machines and a small bird just can't lay hundreds of eggs a year and be healthy.</p>`;

// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>The sheer amount of meat people eat, the prices they want to pay and the number of people eating it has led directly to the industrial factory farm, one of the cruellest inventions of humankind. To meaningfully reduce the suffering of animals in farms, people will have to be far more conscious about what they eat, eat fewer animals and pay more for them. People talk about more humane farms as a “drop-in” alternative, but they simply couldn’t hope to approach the scale. For all that talk about more humane animal farming, few consumers are consistent in supporting them. Why people who eat meat regularly bring up human farming so often in discussion remains a mystery. It's like their fantasies about humane animal farming creep into the real world just enough to absolve their conscience about what is actually going on in the factory farms they are making more profitable at every meal. There are many things we could do and many fantasies we can have but ultimately it is what we do in the real world that counts morally.</p>
<p>Backyard farming has emotional appeal, it tries to replicate the stories we tell children about how animals are farmed. The same stories are often replicated on the outside of the packaging of animal products, the smiling, happy pig on some grass, the rooster crowing to greet the morning sun whilst standing on a fence. Inside the packaging is the dismembered corpse of a prematurely slaughtered animal that often only ever glimpsed the sun between bars or in the truck on the way to the slaughterhouse. Roosters of course rarely get even that far, suffocated in bags, or ground up alive soon after being born. Pigs, cows, large fish, none of these fit into the backyard farmer ideal, but then backyard farming is more about bucolic fantasies than any serious solution to the widespread suffering of farm animals.</p>
<p>So back to the poor chicken, two-thirds of the total bird mass in the world are chickens on factory farms and they are perhaps the most abused animals on earth. If you are thinking of re-homing an animal from a factory farm that would otherwise go to slaughter, whilst a noble idea, it comes with various health and sometimes mental issues for the birds. The modern factory-farmed hen has not been bred with its welfare in mind, it has been bred by large corporations as a profit-making machine. Wild chickens laid one or two dozen eggs split into two clutches each year. The modern factory-farmed chicken has been bred to lay an egg every day. This takes a terrible toll on their small bodies, leeching calcium and other vital nutrients. Animal sanctuaries that take in hens from factory farms often put them on hormones to slow down egg production and give their bodies a chance to heal, though apparently, this isn’t a healthy long-term solution either. Chickens will live up to 10 years naturally, but egg-laying factory-farmed chickens are killed at younger than two years old because to use industry jargon reminiscent of machines "their production falls rapidly" at this stage, in other words, their reproductive systems and bodies are spent. The brothers of these egg-laying hens have almost all been killed as chicks, generally by grinding up alive or suffocating/gassing and note these are the recommended “more humane” ways of killing them as opposed to letting them die of dehydration or putting them in garbage bins alive. In backyard farming they still have the problem with too many male birds, so they are usually grown until they start to mature, from 3 to 4 months, and are then slaughtered to eat. Female birds will live long after their egg-laying starts to slow down, and are also generally slaughtered by backyard farmers as this starts to happen. So backyard farming can alleviate the confinement and cages, but not the slaughter and much of the suffering. I guess it just depends on how much you really need eggs, or can just eat something else?</p>
<p>Factory farms and slaughterhouses are terrible places, and that is even with some oversight by the government and the occasional activist breaking in and documenting conditions in them. The unregulated, unseen nature of backyard farming can lead to more painful deaths, neglect, lower standards of care and hidden abuse. Suffering does exist on a scale, however. If we make assumptions that people would care more about the animals if they raised them, maybe even treat them as part of the family as they often do their pets, it would mean an improvement in animal welfare.</p>
<p>Backyard farming is not going to make much of a dent in the factory farm system though while people continue to consume as they do. The average home would need hundreds of animals to sustain the current levels of slaughter, hardly possible in the suburban houses and apartments billions of people live in. The historically unprecedented amount of animal products wealthy humans eat can only be fed by the industrial factory farm. There are also all the animal products already in products people buy, the food they purchase at restaurants and cafes, and the meals they have with friends and family. Monitoring all of this to ensure it is ethically produced gets so complicated it is probably easier to just be vegan.</p>
<p>Taking a sentient being's freedom away, using its body for profit and production, and prematurely killing them will always be a form of oppression. If this were all humans were capable of surviving on, if we really needed these products to be healthy then maybe kinder oppression would be the best relationship with non-human animals we could hope for. Many millions of people who have gone vegan and are living happy, healthy lives say otherwise. Another world is possible in the relationship between humans and non-humans.</p>
<p>Animals are not on this earth for us, they are here with us. </p>
`;

export {
  heading,
  alternatives,
  short_answer,
  long_answer,
};
