
const heading = `I don't eat much meat`;

const short_heading = `I don't eat much`;

const alternatives = `I am mostly vegan. Someone tells you they recently ate a vegetarian or vegan meal.`;

const short_answer = `<p>Whether you think you eat much meat is partly related to who you compare yourself to. Americans and Australians consume 2 to 3 times the amount of animal products compared to the global average. An American who &quot;doesn&#39;t eat much meat&quot; might be considered an avid meat consumer in Japan, or even in America, before the factory farm changed things so drastically. Someone who eats meat less than once or twice a week can probably claim they aren&#39;t eating much meat. Everyone else should say something more like &quot;I don&#39;t eat as much meat as my red-faced uncle who drives a big car&quot;. Most vegans appreciate the positive aspiration to eat less meat, but it still implies victims. Fewer animals in factory farms means less suffering in the world, but every animal unnecessarily slaughtered for food is an individual tragedy.</p>`;

const long_answer = `<p>People who say things like &quot;I don&#39;t eat much meat&quot; or &quot;I just made a great lentil soup&quot; to a vegan are often trying to connect in some way. So let&#39;s start by saying that this is generally positive on some level, and we should encourage such statements. If someone is reducing their meat consumption or is switching to plant-based milk, this will have positive ramifications for their health, environmental footprint and, usually, animal suffering. Not eating much meat, however, is a relative term. People often base their idea on what is a &quot;normal&quot; level of animal product consumption at the specific time and culture around them. In some countries, average meat consumption is up to 20 times higher than in others. If we are in a culture that eats globally and historically high levels of animal products, when someone says &quot;I don&#39;t eat much meat&quot;,  they might still be eating quite a lot. It is also a vague statement, nothing as direct as &quot;I only eat meat when I am at special events&quot; or &quot;I only eat animal products one day a week&quot;, so we are left to guess at what it means. Perhaps it means people have reduced their consumption, such as eating smaller portions. Perhaps they have swapped red meat for chicken and fish. Perhaps they feel they eat less meat than some of their family members. From a vegan point of view that sees all animal product consumption as unnecessary and unethical, this reduction still looks like eating a lot of animal products.</p>
<h2>The small animal replacement problem</h2>
<p>Perhaps unintuitively, eating less meat doesn’t mean eating fewer animals. How many animals suffer as a result of your diet depends on what species of animals you eat, and at what life stage you eat them. When people consume the body of a veal calf, lamb, kid or piglet, many more must endure the cruelties of our animal farming system because, obviously, infants and children are so much smaller than adults. Chickens, some of the most abused animals in the farming system, are very small relative to pigs or cows. Each person regularly eating chicken flesh and eggs requires a sizeable flock to be kept on their behalf, like a shadow self that suffers on their behalf in factory farms and slaughterhouses. Multiplying this size flock by the number of people who want to eat chickens results in tens of billions of hens imprisoned at any given moment. Fish are another common substitute for other animal products for people concerned about the health of their diet. Fish species vary in size, but many that humans eat are quite tiny, especially sardines, anchovies, shellfish and many crustaceans. As human overfishing assaults our marine ecosystems and the breeding cycles of every target fish species, the average captured fish becomes ever smaller, meaning more fish must be killed in a destructive downward cycle. People who eat less meat by swapping large animals for smaller animals will eat more animals, and thus potentially cause more suffering. </p>
<h2>Collateral damage</h2>
<p>Land-based animal farming doesn&#39;t just involve the oppression and slaughter of target species, but requires the exclusion and killing of non-target, native species. This begins with the deforestation involved, to remove imagined predators, to remove competitor species for animal fodder or water, for often preemptive, poorly researched disease control, to stop animals digging burrows and holes, to prevent them from damaging fences, and the list goes on. While the number of non-target species killed on land is in the hundreds of millions each year, the scale of this killing is dwarfed by the killing of non-target species in our oceans. When you eat any animal from the sea, the animal you actually eat might be a minority of the ones killed to get that sea creature to your plate. All industrial wild-fishing methods are functionally indiscriminate. Longline fishing involves trailing hooks on 10 to 100-kilometre-long lines through the sea; bottom trawling involves heavy cages being dragged across the ocean floor, destroying everything living or otherwise in their path; drift nets or &quot;purses&quot; are huge nets thrown onto target-rich areas to suffocate and crush whatever is in the area. Killing non-target species is called bycatch: wild sentient creatures who suffer and die just to be tossed away as refuse. In drift net and bottom trawling, bycatch often exceeds ninety per cent of all killed animals in industrial wild-fishing. The death in bycatch is often for no purpose at all. The period during which industrial fishing gear is being actively used is often just the start of the death and carnage it will cause in our oceans. Drift nets and long lines often escape or are cut off their moorings and boats to spend decades drifting our oceans as &quot;ghost nets&quot; and &quot;ghost lines&quot;, indiscriminately attracting and killing ocean life for no purpose. Discarded or lost fishing gear will finally break into smaller pieces, becoming a leading cause of plastic pollution in our oceans, including microplastics. It&#39;s not just to feed humans that this assault on our oceans takes place, but to feed our pets, farm animals, plants, and, horrifically but almost absurdly, our land-based fish farms.</p>
<p>So if meat reduction means someone switching their diet from pigs and cattle to chickens and fish, or even from a wild fish to farmed fish, it can mean more animals in factory farms, crushed in nets, harried and herded into slaughterhouses, impaled with hooks or suffocated. Not eating much meat can end up killing more animals. Vegans hear this a lot from well-intentioned people, but it isn&#39;t something we can necessarily celebrate.</p>
<h2>Diet and rationality</h2>
<p>I have often spent time with numerous people who tell me they don&#39;t eat much meat. This might be when travelling together, at work, at conferences and so on. I can&#39;t help noticing that they seem to eat a lot of animal products, every day, at both lunch and dinner, sometimes even breakfast, regardless of whether there are readily available good alternatives. Even if such people gave meat a break for a meal, which is usually only breakfast, the animals certainly don&#39;t get a break, as the meal seemingly has to feature eggs or dairy. There is something more than taste and logic going on here. I&#39;ve met meat eaters who refuse to eat vegetarian meals, and vegetarians who refuse to eat vegan meals, though both groups probably happily eat such meals accidentally reasonably often. I have on a couple of occasions, been out with people who don&#39;t know me well, and I&#39;ve offered to buy a round of snacks for the table. I then ordered finger food like fries, chips, spring rolls, pakoras, cocktail samosas, nuts, and so on, but on none of these occasions did people question the food, and they just ate it happily and thanked me. I think if I had declared, &quot;I will get some vegan snacks for the table&quot;, it would have gone differently, probably with people feeling the need to go and buy their own snacks. A bowl of cereal for breakfast is a vegetarian meal, a bowl of channa masala, daal, bread and rice is often vegan, but if you labelled them as such, many people with an animal product-centric idea of their meals would avoid them. If you asked someone whether they are emotionally attached to having animal products at every meal, they would probably say no, yet here we are. If people really do &quot;not eat much meat&quot;, it might help break this level of emotional attachment; however, if they are just reducing portions or swapping species, it probably won&#39;t. </p>
<h2>Vegetarian myths</h2>
<p>The focus is often on not eating much &quot;meat&quot; because people consider dairy or eggs to be “deathless” industries. This is another sign of how divorced people are from the industries and practises they have paid for via their consumption over their whole life. Even people who claim some connection to these industries, &quot;I grew up on a dairy farm&quot; or &quot;my uncle raises chickens&quot;, can often, with a few basic questions, be shown to be largely unaware of the cruelties which take place as standard practise in these industries. We shouldn&#39;t expect a better understanding from people who grew up in urban environments, and equate animal body parts and products more with their packaging than the sentient, emotional beings they came from. A short list of examples has to be made here, though people should take the time to confirm these things for themselves. Male chickens are killed immediately after their gender is detected, often fed alive and en masse into grinders. Their sisters go on to spend a life of suffering before being killed when their reproductive systems are spent at a relatively young age. Dairy cows are repeatedly impregnated to keep milk production high, which means the regular production of male calves that must be taken and killed. This is usually within a few days of them being separated from their mothers, but “humane” veal farms might let the male calves live a few months before slaughtering them. A minority of males will instead be castrated and dehorned without anaesthetic, allowed to grow for a year or two before being slaughtered for low-grade meat production. Females in the dairy industry are also, if needed, dehorned without anaesthetic, and kept alive only while their reproductive systems enable peak profitability. After milk production slows at a relatively young age, they are destined to be herded onto crammed trucks, for a journey during which they are neither fed nor given water, that ends in the trials of the slaughterhouse. The dairy industry is a vast environmental and animal welfare disaster. These are just some of the cruelties and injustices that are an integral part of eating animal products, even beyond meat, in our society. If you are serious about contributing to a better world with your diet, swapping meat for eggs or cheese might mean fewer animals suffering, but many of those animals can suffer more.</p>
<p>The ethical and environmental case for dramatically reducing our global dependence on animal products is unassailable, despite people, out of habit and self-interest, trying to argue otherwise. According to our peak dietary bodies, average meat consumption in many developed countries has become too high. Health authorities consistently encourage populations to reduce meat consumption, particularly of processed meats, in favour of more fruits, vegetables, whole grains, beans, etc. Many developed countries would see significant environmental and animal welfare improvements by people simply following their peak nutritional authorities&#39; dietary recommendations, not to mention human health. Agriculture is a world-dominating industry, and animal agriculture is the most unnecessary and destructive part of it, whether we talk about deforestation, species extinction, pollution or climate change. We can do a lot of good for ourselves and the world by eating a healthier diet of more plant-based, whole foods. The world&#39;s peak dietary bodies also confirm that a well-planned vegan diet is a healthy choice at all stages of life. There is no physiological necessity to eat animal products; if people are mostly doing this out of habit, then it is a habit we must collectively replace to tread more lightly on the earth.</p>
<h2>Inculturation</h2>
<p>If one had to guess what somebody eats without knowing anything about them, a decent approximation would be to look at what their parents eat. Our inculturation to a specific form of eating starts when we are toddlers. We don’t put much thought into how we came to eat what, or who, we do, but over our lives, we have been taught a specific cultural diet. We have learned a taste for particular things, become accustomed to a certain level of salt, sugar and fat in our foods, certain types of spices, and learned what foods are appropriate at certain times of the day. Cultures put their own largely arbitrary constructions around the very basic need to get certain nutrients into our bodies. We can see all the cultures around the world happily eating very different diets, yet many picky people would be very upset if they had to swap diets with a similarly picky person from another culture. No doubt if we had been raised in a different culture, we would have very different tastes and preferences. Diets are, after all, beyond the nutrients, pretty arbitrary. Yet if many people were forced to eat as a different culture does, they would be uncomfortable, resist, or possibly even angrily resist. It&#39;s irrational, but then most people live largely irrational lives that they have no desire to question. Vegans are asking people to change their diets for compassionate reasons rather than arbitrary cultural or aesthetic reasons, but we will still often face the same instinctive, irrational resistance. Diet is a pretty deep thing to change, so when people say they don&#39;t eat much meat, that might be as far as they can go without severing the links of the shared, arbitrary identity they mistake for their individual, consciously chosen self. If we wish to change this, it may not be through the rational mind we need to go, but doing things like exposure therapy to vegan food and thought, to slowly shift cultural perceptions and open up a crack to a different self, one that has the courage to look unblinking into an uncomfortable ethical reality that their consumption makes them complicit in.</p>
<p>Comparison is a large and not always productive part of our identity. When people say they don’t eat much meat, they aren&#39;t comparing themselves to their great-great-great-grandparents&#39; generation, which ate quite differently. While the world population has more than doubled since the 1960s, livestock production and consumption have more than quadrupled. Academics call the changes in diet that have happened in almost every country post-World War II the modern nutritional transition. This has been enabled largely by factory farms, fertilisers, pesticides and intensive breeding. People don&#39;t have a good understanding of this change and how much it has altered our world and our diets. Many people mistakenly think that meat has always been as central to their national cuisines as it is today. I have had conversations with people of varying nationalities who believe that not only is their national diet currently meat-heavy, but that it has traditionally always been so. </p>
<p>People from Spain, Japan and South Korea have all told me some version of, &quot;My country is traditionally a heavy meat-eating culture&quot;, and on each occasion, I looked them up:</p>
<ul>
<li><p>Spain - Transitioned away from a Mediterranean diet, with one of the lowest per capita levels of meat consumption in Europe, to one of the heaviest via a 400% rise in average meat consumption since the 1940s.</p>
</li>
<li><p>Japan - Transitioned away from a rice, vegetable and marine animal diet via a 700% rise in average meat consumption since the 1940s. For centuries, various types of animal products, including beef, chicken and eggs, were banned from consumption across Japan. These bans were only entirely lifted with the Meiji restoration and modernisation reforms in the 1850s.</p>
</li>
<li><p>South Korea - Transitioned away from a heavily rice, vegetable and marine animal diet via a 600% rise in average meat consumption since 1970. In Korea, a country that has a proverb meaning &quot;Living through the power of rice&quot;, meat has now overtaken rice as the most consumed product.</p>
</li>
</ul>
<p>These countries are just examples of a global trend. Current levels of meat consumption around the world have increased dramatically alongside the spread of the factory farm, often replacing healthier, traditional plant-rich diets. Modern farming techniques and intensive breeding pioneered by heroic individuals like Norman Borlaug, along with a vast new range of pesticides and fertilisers, have increased production to the point that a global majority can now get more calories than they need. Obesity is now as much of a health problem in the world as hunger has always been. While this increase in the quantity of food and calorific availability is rightly celebrated, the quality and variety of diets, such as the traditionally healthy diets of places like Spain, Japan, and Korea, have declined in many ways. By being so much more dependent on animal products, there has certainly been a sharp increase in their ethical ramifications, for which there is yet to be a proper reckoning.</p>
<h2>Evolving together</h2>
<p>Moving to a better relationship with the earth requires large structural changes, but these can only be constructed on billions of individual changes. We live in a culture that has not adapted our individual behaviours to ever-evolving environmental and ethical realities, including those that modern technology and a surge in human population have created. This means that when we look at obvious facts, like that most of us are living lives far beyond the environmental tolerances of the earth, or that the way we eat requires immense cruelty and oppression of other species, we cannot necessarily look to the people and culture around us for positive role models for change. Often, the opposite is true; instead of helping us to be our best ethical selves, we live in a culture that makes it easier to continue living in an unethical way. This means it will take an effort of will, and our character will constantly be tested if we try to make the significant changes needed to live in a more compassionate way. For many of us, these positive choices and changes might need to be gradual, as we reorient lives out of sync with our ethical ideals. Taking time is understandable whilst new habits are acquired and new ways of eating and thinking become embodied in our lives. Not making those changes, however, would be to turn aside from our authentic self, to a comfortable cultural construction that is a tyranny on other life.</p>
<p>In the end, we should generally try to be kind to people who hold out a hand towards us. &quot;I don&#39;t eat much meat&quot; is a statement of positive intention, and if properly followed through with, it will mean the ramifications of their lives on the non-human world will be less bad. We should have higher ideals for ourselves and our contribution to the world than less bad; we should be heading towards flourishing and a higher good. A better collective future awaits humans and animals beyond the factory farms, cages, barbed wire enclosures, slaughterhouses, and other tools of animal oppression that humans have created. Not eating much meat leaves these things that should never have existed in place. A collective evolution to a global vegan culture is too important for us to linger in the ethical purgatory of transitional phases. Be part of leading that change.</p>`;

export {
 heading, short_heading, alternatives, short_answer, long_answer,
};
