// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `Plants have feelings`;


// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `Carrots scream when you cut them. Growing plants kills more animals than livestock production`;


// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>The science of plant consciousness is evolving but does not ascribe them higher levels of experience. On the other hand we know that cows, sheep, pigs, horses, chickens, dogs and other animals people eat have high levels of sentient experience and central nervous systems similar to our own. If we want to reduce suffering, especially our personal contribution to suffering, then our ethical responsibility is clear, to reduce the animals in our food system. If in the future we find that plants have high levels of consciousness we will need to reconsider our ethics, but for now we should focus on the world that presents itself to us, the one in which many billions of animals along with uncounted numbers of fish, suffer and die unnecessarily for our food.</p>`;


// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>Unfortunately people who pose questions like this are rarely next-level compassionate philosophers seeking personal improvement. Usually they are less likely  to care about plants, forests and ecosystems under attack from human encroachment than the average person. No they are seeking intellectual justification. The last thing they want is to question their own beliefs, and are instead diverting the moral question of how they treat animals somewhere else. Humans have a long history of this sort of displacement, confronted with potentially uncomfortable ethical introspection, they eagerly seek out the foolishness, duplicity and immorality of others. A ridiculous conversation trying to establish intellectual superiority feels a lot better than pondering and acknowledging your own ethical shortcomings.<p>


<p>What about plants? What are your shoes made of? What about people? “What about” questions are transparent displacements from seriously comprehending the meaningful and important question of animal suffering in our world. It is understandable, we fear judgement, we fear painful thoughts, uncertainty, change, but they are the price we must pay to live ethically. The immense scale of human caused suffering in the farming industry cannot be brushed away by anyone of any emotional or empathetic depth. Doing so is what the ancient philosophers would call Sophistry, a lack of serious engagement with the questions of life beyond the most trite and surface level. In Alexander Solzhenitsyn’s Nobel Prize winning noval the First Circle, a character says “When I was young I thought I understood philosophy but now I know I didn’t then understand philosophy”. Asking questions like “What about plants” says something similar about ethics, that the unnecessary suffering of billions of obviously sentient beings can be waved away or ignored by a trite comment or a clever quip.</p>


<p>Conveniently many people’s ethical opinions align perfectly with and justify what they have always unthinkingly done, which is usually what their parental figures unthinkingly did and so on. Apparently the ethical life philosophers have been debating for centuries doesn’t need change or careful reflection, we all just needed to keep doing what we have always done out of habit, justifying it after the fact. Living ethically is unfortunately rarely so simple and part of the journey is constantly questioning our habits and cultural frames of reference. Moral character is grounded in following the truth wherever it leads, embarking on an open, honest and introspective dialogue which fearlessly questions our moral oversights and failings. There is a world beyond our sight that we are part of creating, and therefore we have some moral responsibility for it. Justifying the terrible lives and slaughter of sentient beings should clearly be held to a high ethical and philosophical bar. Merely using our intelligence to displace it is a sign that we fear the ethical mirror, we fear questioning our treatment of the lives we affect, lives with less power and agency than us.</p>


<p>Most of the animals we eat are herbivores, fed from the same farming system that we use to feed humans. Something like a third of the grain eaten in the world, and a higher percentage in developed countries, is used to feed livestock. Animals, especially larger ones, are inefficient converters of plant foods into edible human protein. Eating animals fed on plants means many more plants are needed to feed us than if we just ate plants directly. The same logic follows for the animals killed as a byproduct of growing plants, vegans kill less of them because they avoid inefficiently cycling nutrients through other animals. It is revealing that meat-eaters only begin caring about the animals killed as a byproduct of their food system when they think it could be a tool to intellectually beat people questioning their ethics with. Vegans actually do care about these animals for their own sake, and it is only a farming system with a more vegan ethic that will start to more seriously look at how to minimise these unfortunate deaths. For the world as it is, a vegan diet is not without death, but it involves far fewer deaths, and provides a firmer basis for lowering that number further.</p>


<p>Plants have their own evolutionary journey on this planet that we should respect. It is an interesting and evolving question what our duty to them is. Beings deserve ethical consideration appropriate to their level of sentience. Plants don't have a central nervous system because its not evolutionary useful to feel intense pain if you can't do something in response to it like run away. Plant biology is many and varied though, there is a lot to be said here but such nuances might be lost on anyone belligerent enough to ask this question. Still, we should try to assume the best of people, that they ask questions or make statements sincerely, and treat it as an opportunity for shared growth. So taking the question seriously, consistent with evolutionary theory there aren't distinct, easily identifiable separate kingdoms of plants and animals, it is very much a continuum, a web of interrelated life stretching out over time and space. We do need to continually question ourselves what our ethical duties are and on what basis we make our judgements, of what life deserves what consideration. There are people who take animal suffering very seriously who think eating simple creatures like oysters and mussels, or eating honey or other insect products are ethically justifiable. Vegans wouldn't do this, but we generally have greater respect for people who have thought things through and made ethically motivated changes than those who unconsciously accept whatever ideas they grew up among. For many societies in human history cannibalism, human sacrifice, slavery, class, caste and many other things we now think are unethical were cultural norms. History teaches us that questioning the received wisdoms we were raised within is a requisite precursor to ethical progress.</p>


<p>Darwin and most eminent biologists since have understood that the common evolutionary heritage with other creatures expresses itself through us, we share the core of our sentience with other beings. Humans are not a different kind of being, we are those beings with some differences and additions, we do not experience existence completely differently to them and thus exist in a separate moral universe. Many vegans follow a philosophy called sentientism, that all animal’s interests deserve consideration according to their level of sentience. This is opposed to speciesism, which treats all non-human life as having lesser worth, not because of their innate capabilities, but purely because they are not human. Similarly, speciesism questions why animals on factory farms are treated so inhumanely, when they are just as worthy of kindness as the cats and dogs that people often lavish affection on and consider members of their family. If someone agrees it is cruel for a faaily not to walk their dog regularly, but then unquestioningly eats pigs who’s life has been the factory farm and the slaughterhouse, then they clearly have a lot of ethical progress to make.</p>


<p>Humans are a powerful, often destructive force on the processes of life in our world, and modern technology only increases this. As our collective footprint upon the world grows it is ever more urgent that we reconsider our philosophies and ways of living as they relate to the non-human world. The factory-farm, the chainsaw, advanced breeding techniques, the incredible rise in human population are products of modernity, we cannot ethically guide our technological advancement with the same thinking and philosophies of the past. We need to continually re-evaluate our moral framework, and carefully reconsider where we draw our moral lines and what our obligations are to the other beings who share our world.</p>


<p>Other life is here with us, not for us, it has its own story and place in evolution that should not be automatically subservient to human desires. If we do find that plants have high levels of sentience, we will have to re-evaluate our positions in order to most ethically sustain ourselves. For now though, something much more obvious and uncontroversial is staring back at us from the behind barbed wire, metal bars, cages and nets, We know without question that the animals in our factory farms and slaughterhouses definitely do think and feel deeply, they share many of our emotions, the same senses of pleasure and pain. We know that eating fewer animals will benefit both the flora and fauna on our planet.</p>


<p>It is the lot of our finite minds in this infinite universe to have to act with limited knowledge and information, we will inevitably make mistakes practically and ethically. It is not making mistakes we should fear, but the mindset that refuses to grow, to learn and then change when confronted with new information. We can never have complete certainty about the intellectual and emotional lives or other animals, or even other people, but when limited knowledge confronts ethical questions history teaches us that it is almost always better to err on the side of compassion.</p>
`;


export {
  heading,
  alternatives,
  short_answer,
  long_answer,
};