// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `Vegans are preachy`;


// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `The sadly ironic "live and let live". Each to their own. What I eat is a personal choice.`;


// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `<p>Like any large group, veganism will have people with varying social or communication skills. How someone presents an idea however, is irrelevant to its truth. Rather than shooting a messenger unsettling our mind with the suffering of non-human animals, ideally we would try to see it as an opportunity for introspection. Building ethical character is a personal moral journey, not one that should be guided by the vagaries of social interaction. Forgetting our part in the deeply unfair relationship humanity has with all other life in this world because we met someone interpersonally inept is illogical and unjust.</p>`;


// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>Some people just need to chill out a bit. Among the millions of vegans, like any large social group, there will no doubt be a share of these people. Vegans reflect the diversity of people, in all our normal human flaws and biases, Still veganism is an idea, not a group of people. Engaging with veganism on any other level is to miss the forest for the trees.</p>
<p>Anyone who has had bad experiences with a preachy vegan should try this social experiment for a while: try saying you are vegan. When you see what sort of repetitive conversations and reactions ensue you’ll realise there’s a reason “Vegan Bingo” exists. Generally most people are considerate, a few are even interested and wanting to know more. Some people seem to have a major prejudice against it however, especially those most fixated by their masculinity identity. For all the preachy vegans in the world, there are more preachy and angry people who think veganism, the idea that we should be more compassionate towards non-human animals, is a personal affront.</p>
<p>Many vegans have been in the situation of asking about vegan options when ordering a meal, having someone else at the table overhear this and begin to ask simplistic and hostile questions. It’s not easy to stay relaxed under interrogation, to remember when confronted with negativity the adage “never argue with a fool, people won’t know the difference”. It’s actually worse than just arguing with one fool in many social situations, the fool is representing the majority opinion. Anyone arguing against a mob will be held to a higher standard intellectually and emotionally than interlocutors who are arguing for the same “team” the mob is on. We must not only be able to express the many good reasons for being vegan well, we must also pay more attention to how we carry ourselves to give our message some change of being heard, or at least not being counter productive. We may protest that an idea should only be judged on things like it’s ethics or logic, but we need to accept we don’t often live in that world.</p>
<p>But we still need to talk about preachy vegans. I’ve read the books, watched the videos, heard the cries from within factory farms, smelt the stench that the farmed animals are kept in. I know and feel the emotional angst preachy vegans are expressing at all of this unnecessary human-caused suffering, you feel you just want to wake people up ethically. But other people probably don’t know or engage with these things, all they see is an angry person in front of them, trying to get an emotional response towards something pretty negative. Perhaps they see us trying to sell some idea just like all the religions, politicians, marketers, salespeople and other charlatans. We need to express ourselves in such a way that makes clear we are not like those people, that we are promoting the interests of animals, not ourselves.</p>
<p>People often talk about “not preaching to the converted” but that is generally wrong, you need to preach to the converted, to educate and inspire them, but to the unconverted, you need more subtle and thoughtful ways of engaging. People who already agree with you may cheer your angry preaching on from the sidelines, preaching might even have some value from that perspective, but it’s probably not effective in changing the unengaged people you are targeting, people who will hold your arguments to a much higher standard than people who already agree with you.</p>
<p>Whilst discussing perspective, it’s interesting what is considered preaching and what isn’t. When local activists erected a billboard showing an injured racehorse lying on its side (the horse was later killed), they were forced to take the billboard down as a disturbing image. However, our suburbs are littered with billboards displaying burnt animal parts considered food because that is socially acceptable. It’s not just what you see that creates your world but also the story you tell yourself about it. Is that a piece of food or the burnt flesh of an overly bred, malformed animal murdered prematurely after a terrible life? If you see only the former, you probably won’t understand anyone trying to talk about the latter. You might even subconsciously resist seeing the latter because it is psychologically discomforting and ethically inconvenient, it may require you to change, or to give up ideas you take for granted from within your current frame of reference. The task of advocating for animals is not just putting information out into the world, we have to help people open themselves to uncomfortable information in a way that doesn’t provoke emotional self-defence mechanisms and that is considerate of other traumas that people might already be dealing with. None of this is easy, but it is probably what is needed to best help animals.</p>
<p>If I was an animal bred in a factory farm or on my way to slaughter, I’d desperately hope someone would speak on my behalf. More importantly though, I’d want them to be effective. Even if you are right it is not enough to shout at the world in anger, the point is to change it, to move it forwards, to direct your emotional energy towards productive ends. People rarely change from one fact, phrase, sign, interaction or conversation, the world is unlikely to radically change tomorrow. We are playing a long-term, structural, game of power and cultural change. Emotions are important but should be harnessed carefully so that we play this game effectively.</p>
<p>We can speak the best for animals by engaging people's higher selves without overly provoking their anger, guilt, shame or defensiveness. Those who demonstrate the same compassion and understanding towards people that they advocate towards animals are generally the most effective advocates for animals.</p>
<p>If you want to be an effective vegan advocate, even a preachy vegan, you need to do the work. Read about psychology and effective behaviour change, the history of our movement and its thinkers, the arguments and justifications of the other side, the lives of farmed animals, the livestock industry’s effects on the environment, human rights and our political systems. Whilst facts can be important, primarily if you want to be effective you should seriously consider other’s points of view, make them feel heard and look for common ground on which to build. Keep in mind before we judge others that most of us haven’t always been vegan and even then usually have other areas to ethically improve upon. There is also the question of effectively using our emotional resources and time. The random people you meet on a street, who walk past a protest, even friends and family, may not be the subset of the community most open to change. Activism doesn’t have to be confrontational, it can actually just be helping people to live according to their ideals. There are so many people who are ready to change, people who just need advice rather than a radical new worldview. Being part of an activist group can help here, to come up with plans and campaigns that are well thought through, rather than personally focusing on the arbitrary people you know that may be resistent to change.</p>
<p>Like it or not, whatever identity we have, especially if we are a minority, we will be a representative of that identity in the world. To be an effective advocate for animals we must understand that the medium and the message are inextricably intertwined. Wearing a judgemental shirt, shouting angrily at the world may feel powerful, it may even win you approval within certain circles, but is it effective?  Veganism is about compassion, try not to confuse that simple truth in other people’s minds.</p>
`;


export {
 heading,
 alternatives,
 short_answer,
 long_answer,
};