// This appears under the pictures on the square, and at the top of its
// individual page.
// Format: Text.
const heading = `Vegans are preachy`;

// These are the alternative questions/acceptable statements at the top of the
// individual page.
// Format: Text.
const alternatives = `The sadly ironic "live and let live", each to their own, or "How do you know someone's vegan? Don't worry they'll tell you"`;

// This is the short section at the top of the individual page.
// Format: HTML.
const short_answer = `How someone presents an idea is irrelevant to the truth. Like any group of people, veganism is going to have its share of those with varying social or communication skills. Rather than shooting the messenger who brings disturbs your attention with the suffering of non-human animals, maybe see it as an opportunity for reflection and progress. After all, we know something is deeply unfair and wrong in our relationship with the other creatures who share our planet, ignoring that because some people have poor communication skills would be unjust.`;

// This is the body of the individual page, use HTML liberally.
// Format: HTML.
const long_answer = `
<p>Some people just need to chill out a bit. Among the millions of vegans, like any large social group, there will no doubt be a share of these people. Vegans reflect the diversity of people, which is cool but also means we have all the normal human flaws and biases, Still veganism is an idea, not a group of people, engaging with veganism on any other level is to mistake the forest for the trees.</p>
<p>Anyone who has had bad experiences with a preachy vegan should try a social experiment: try saying you are vegan for a while. See what sort of repetitive conversations and reactions ensue, there’s a reason “Vegan Bingo” exists. Generally, most people are fine, considerate, a few are even interested and wanting to know more. Some, however, especially those who are most fixed in their masculinity identity, seem to have a major problem with it (often not just veganism either). For all the preachy vegans in the world, there are at least as many preachy and angry people who think veganism, the idea that we should be more compassionate towards non-human animals, is a personal affront. Many vegans have been in the situation of ordering a meal, asking about vegan options, and having someone at the table pick up on it and start asking increasingly hostile questions. It’s not always easy when confronted with negativity to remember the adage “never argue with a fool, people won’t know the difference”. We have to try though, to maintain the high ground, because you will be held to a higher standard if your angry interlocutor is arguing for the same “team” that the people around you are on.</p>
<p>But we still need to talk about preachy vegans. I’ve read the books, watched the videos, I’ve heard the cries from within factory farms, I’ve smelt the stench that the farmed animals spend their lives in, I know the emotional angst preachy vegans are expressing at all of this unnecessary human-caused suffering. But other people probably don’t know or engage with these things, all they see is an angry person in front of them, trying to get an emotional response towards something pretty negative. Perhaps they see them trying to sell some idea just like all the religions, politicians, marketers, salespeople and other charlatans. We need to carry ourselves in such a way that it is clear we are not like those people. Activists often talk about “not preaching to the converted” but that is generally wrong, you need to preach to the converted, to educate and inspire them, but to the unconverted, you need more subtle and thoughtful ways of engaging. People who already agree with you may cheer your angry preaching on from the sidelines, preaching might even have some value from that perspective, but it’s probably not effective in changing the unengaged people you are targeting, people who will hold your arguments to a much higher standard than people who already agree with you.</p>
<p>Whilst discussing perspective, it’s interesting what is considered preaching and what isn’t. When local activists erected a billboard showing an injured racehorse lying on its side (the horse was later killed), they were forced to take the billboard down as a disturbing image. However, our suburbs are littered with billboards displaying things like pieces of animal flesh on rotisseries, literally impaled and rotating in flames. It’s not just what you see that creates your world but also the story you tell yourself about it. Is that a piece of food or the burnt flesh of an overly bred, malformed animal murdered prematurely after a terrible life? If you see only the former, you probably won’t understand anyone trying to preach about the latter. You might even subconsciously resist seeing the latter because it is psychologically discomforting and ethically inconvenient, it may require you to change, or to give up ideas you take for granted from within in your current frame of reference. The task of advocating for animals is not just putting information out into the world, we have to help people open themselves to uncomfortable information in a way that doesn’t provoke emotional self-defence mechanisms and that is considerate of other traumas that people might already be dealing with.</p>
<p>If I was an animal bred in a factory farm or on my way to slaughter, I’d desperately hope someone would speak on my behalf. More importantly, I’d want them to be effective. Even if you are right it is not enough to shout at the world, the point is to change it, to move it forwards. The world is unlikely to radically change tomorrow, we must play the long-term, structural, considered game of power and cultural change.</p>
<p>We can speak the best for animals by engaging people's highest selves rather than their anger or guilt. Those who demonstrate the same compassion towards people that they advocate towards animals will be the most effective advocates for animals.</p>
<p>If you want to be a preachy vegan, do the work, read about psychology and effective behaviour change, the history of our movement and its thinkers. If you want to be effective learn to listen to others, consider their point of view and make them feel heard and look for common ground on which to build. Keep in mind before we judge too harshly that most of us haven’t always been vegan, and still have other areas of our ethics we could improve upon. Also remember the random people you meet in life, strangers, friends and family, may not be the best focus for your activism and may not be the subset of the community most open to change. Find those people, push at open doors.</p>
<p>Like it or not, whatever identity we have, especially if we are a minority, we will be a representative of it in the world. If you want to be an effective advocate for animals, you must look to your social skills, the medium and the message are inextricably intertwined. Shouting angrily at the world may feel good, powerful and affirming, it may even win you approval within certain circles, but remember this isn’t about you.  Veganism is about compassion, don’t confuse that simple truth in other people’s minds.</p>
`;

export {
  heading,
  alternatives,
  short_answer,
  long_answer,
};
