
const question = `Where do you get protein?`;

const short_question = `Protein?`;

const alternatives = `Where do you get iron? What about some obscure trace element (that they didn’t know about 2 months ago)?`;

const summary = `<p>When you mention you are vegan, many people suddenly become very interested in your nutritional requirements. Unfortunately, common knowledge hasn&#39;t caught up with the fact that most nutrients, including protein, originally come from plants. There are no essential nutrients that humans need that can only be derived from animal products, and the peak nutritional bodies affirm that a well-planned plant-based diet is healthy for all life stages. Healthy vegans don’t just remove things from their diet, they add other nutrient-rich foods in their place. By doing this, you can optimise your health, while reducing your contribution to animal suffering and environmental destruction.</p>`;

const discussion = `<p>At a party many years ago, a boy of roughly 10 was bringing around a plate of snacks. I declined the offerings but mentioned I’d be interested in any vegan ones. He then promptly asked me where I get my protein from. I&#39;d heard this question many times before, but something about his young age and the speed with which he asked this question took me aback. When an exact repeated statement is so prevalent in culture that it is imprinted in the heads of children, we must wonder how it got there.</p>
<p>My doctor has never asked me about my protein intake, for good reason. Protein deficiency is extremely rare in wealthy countries. People with a diverse and adequate caloric diet, vegan or otherwise, easily obtain the recommended amounts of protein. Protein is in a lot of foods, so we are getting portions of it all the time. Even if someone ate nothing but potatoes, so long as they ate enough to maintain their overall weight, they would come very close to meeting their daily protein requirements. So why are non-vegans obsessed with protein above the myriad other things that people need to be healthy? B12, for instance, is harder to get on plant-based diets, so vegans should supplement their B12. Vegans are rarely asked about B12, however, or anything else similarly well-informed; instead, we get asked over and over again about protein.</p>
<h2>Plant protein primer</h2>
<p>Despite the concern around how much protein vegans are getting, the people who ask about protein rarely know how much we need or how much is actually in different plant foods. There’s no shame in not knowing everything about nutrition; we aren’t born knowing such things, but it would seem reasonable to investigate a little before you criticise a particular diet or dole out nutritional advice.</p>
<p>How much protein you need changes according to a number of factors, such as life stage and your fitness goals. Recommended daily intake ranges from 0.75 grams of protein per kilo of bodyweight, to up to 2 grams for elite athletes. Most dietary bodies have public guidelines you can follow, and you could consult a qualified nutritionist. Once you have a daily target for your protein intake, it&#39;s worth checking your current diet to see how much you are already eating. A food diary kept over a couple of representative weeks that can be checked against a nutrition database will give you a world of information about your intake of protein and other nutrients. Everyone should probably do this every few years to improve their diet.</p>
<p>There is the concept of complete and incomplete proteins. The body produces most of the amino acids we need, however there are a number we need to get from our diet. A complete protein contains all of the necessary amino acids in it, and they include animal products but also soy, quinoa, amaranth and buckwheat. Then there are incomplete proteins, including other nuts, legumes and wholegrains. It was once thought that if you were eating incomplete proteins, it was necessary to combine them so that your meal formed a complete protein. The classic example would be eating beans and rice, which together form a complete or perfect protein. Current research says that the body is smart enough to do this on its own, and as long as you eat a variety of wholefoods you will be fine. Eating more quinoa won&#39;t hurt though!</p>
<p>You can also get a variety of plant based protein powders. These are commonly available and similarly priced to other protein powders. Many are based on rice, soy, pea, or hemp protein, though the variety is quite vast. If you want to get one that provides a complete protein, blends are available. Again, though, if you already eat rice or wheat every day, take a pea or soy-based protein and your body will combine the amino acids into a complete protein.</p>
<p>Many high-profile athletes, including Olympians, weightlifters and bodybuilders, follow a vegan diet. Clearly, these elite athletes are getting what their bodies need for peak performance. Nearly all of them will be consulting nutritional professionals to make sure their diets are meeting their specific needs. We can all emulate these elite athletes and eat healthier diets that are also kinder to animals and the planet. </p>
<h2>Sexual politics</h2>
<p>A hint as to where the protein question derives from is the gender of the people who usually ask about it. Many men obsess about their masculinity, which they relate to strength and muscle, and a single nutrient, protein. Protein, though, isn&#39;t the only thing required in the complex process of building muscle. We need enough calories to drive the growth process, fats to produce hormones, and carbohydrates to maintain energy levels. Still few people ask vegans if we are getting the right mix of healthy fats.</p>
<p>The masculine aspects of killing animals and eating meat have a long history in the human psyche. Most forager societies had gendered tendencies around the division of labour, with men taking on more of the hunting tasks, especially of larger animals. Men tend to be larger, stronger, and more expendable from an evolutionary perspective. Given that men focused more on this high-status task, it will come as little surprise that studies show that most diets in the Palaeolithic era were heavily plant-based. </p>
<p>The association between masculinity and violent killing, like many of our evolutionary tendencies, has been ripe for exploitation by the marketing industry. There has been a sustained and well-funded marketing effort to tighten the association between masculinity and meat-eating. Typical of this were the high rotation advertisements on 1980s Australian television. The ad&#39;s focus is on a sports jersey-clad young boy, and it starts following him as he runs home. The scene then switches to a father reading a newspaper while seated at a table with the boy and his sister. The mother emerges from the kitchen with the burned, severed leg of some poor animal on a plate. There is no subtlety about the messaging here, or any thought to the diet of the women in the ad; the tagline is &quot;Feed the man meat&quot;. Studies have shown that even female vegetarians view men who abstain from meat as more feminine (though they omit to mention whether the female vegetarians thought that was a good thing). There is inarguably a sexual politics of meat. Masculinity is aligned with killing; the more toxic masculinity, the more it celebrates and reinforces this alignment. Instead of clinging to their toxic masculinity like a security blanket, if many men could free themselves of it, we could all progress a little faster to a better world for humans and animals. Women tend to eat less meat than men, the majority of vegans are women, and women generally hold more pro-social views. It was those who tended to gather rather than hunt who had things right all along.</p>
<h2>Corporate propaganda</h2>
<p>Decent people don&#39;t want to participate in cruelty. To make them do so, the cruelty must be mostly hidden, or they must be convinced that it is necessary. Meat and dairy industry propaganda reaches far more people than unbiased nutritional advice. The industry has long used its financial and political sway to ensure a dominant voice on government nutritional panels and has been repeatedly successful in watering down attempts to make national eating guidelines healthier. They maintain this propaganda war because nutritional science often contradicts perceived national and regional financial self-interest. Not only do we not need to eat animals, but some of the most highly profitable forms of animal products that governments help promote are actively unhealthy. The International Agency for Research on Cancer, a part of the World Health Organisation, has listed processed meats like bacon as a known cancer risk, and red meat generally as a probable cancer risk.</p>
<p>National eating guidelines have been very slow to recognise plant-based sources of protein, such as lentils, one of the first crops ever domesticated, or tofu, which has been part of the Asian diet for at least two thousand years. This long-overdue change in guidelines has happened because they are increasingly being asked to respond to science and human health rather than to economic interests. That this change has correlated with fewer purely patriarchal governments and more women in positions of power generally is unlikely to be purely coincidental. We can not take this improvement for humans and animals for granted, however, as it is under constant assault from the entrenched interests of the animal product industry.</p>
<h2>Science and plant-based diets</h2>
<p>The modern scientific understanding of dietitians about plant-based diets has been slow to filter outwards, even in the wider medical community. I&#39;ve had an elite cardiologist ask me where I get my protein from, and I know many people who have heard such poorly informed things from doctors and medical specialists. Unfortunately, most medical professionals don&#39;t get anything beyond elementary nutritional training and are as susceptible to the unquestioned and outdated ideas cluttering up our culture as everyone else. One study found that doctors in the US and UK got about 11 hours of nutritional training during their long degrees. If we look at the opinions of professionals who have completed an in-depth study of nutrition in their degrees, dietitians, we usually see a very different story. The public stances of peak nutritional bodies around the world generally state similar things to the following position of the Academy of Nutrition and Dietetics:</p>
<p>Appropriately planned vegetarian diets, including total vegetarian or vegan diets, are healthful, nutritionally adequate, and may provide health benefits in the prevention and treatment of certain diseases. Well-planned vegetarian diets are appropriate for individuals during all stages of the life cycle, including pregnancy, lactation, infancy, childhood, and adolescence, and for athletes.</p>
<p>For vegans, there is an important point here we shouldn&#39;t ignore. Vegans need to take note of the words “appropriately planned” from the Academy of Nutrition and Dietetics quote above. The idea that vegan diets are always good is almost as ill-informed as the idea that they are always bad. Vegan diets aren’t a magic bullet. Like all diets, they can be unhealthy if they contain too much sugar, oil, fat and fried food, and don&#39;t contain enough fruits, vegetables, pulses and whole grains. Perhaps the easiest test of the healthiness of a vegan diet is how often they include whole beans and lentils. A vegan diet is different to the one people in our modern world grew up with, so there might be some learning and adjustment needed, particularly if people grew up in a family following a meat-centric, highly processed foods diet and haven&#39;t experienced how to cook any other way. A healthy vegan doesn’t just remove animal products from their diet; they add new things to them. There is a whole world of ingredients vegans and non-vegans should be more familiar with, particularly the incredible variety of beans and legumes that have been staples of human cultures for so long. </p>
<p>Vegans who eat a whole foods, plant-based diet don’t need to worry much about things people who eat too much meat and processed foods struggle with, such as fibre, antioxidants, healthy fats, vitamin C and the other goodies fruits, vegetables and plant protein sources are loaded with. Instead, people on plant-based diets should keep an eye on having adequate sources of things like calcium, D vitamins and omega-3s, and of course, B12 which we need to supplement.</p>
<p>In the end, we should be getting our nutritional advice from qualified dietitians, not friends, family, random people, social media or even what you are reading now! A great investment in improving your health is booking a couple of sessions with a university-qualified nutritionist who understands plant-based diets. They will help you ensure your diet is working towards your long-term life goals. People can become overly obsessed about food, so it&#39;s not about purity, but getting the core of your diet right will serve you well for life. </p>
<p>Healthy food is a gift we can give ourselves and others, that will help maintain physical and mental health, and that will reverberate positively out into the world. As a quote attributed to Hippocrates says, &quot;Let thy food be thy medicine&quot;. Let us follow this advice while also ensuring our food is kinder to animals and the environment.</p>`;

export {
 question, short_question, alternatives, summary, discussion,
};
