
const heading = `Where do you get protein?`;

const short_heading = `Protein?`;

const alternatives = `Where do you get iron? Or an obscure trace element that they didn’t know about 2 months ago`;

const summary = `<p>When you mention you are vegan, many people suddenly become very interested in nutrition. Unfortunately, they generally don&#39;t know that most nutrients, including protein, come from plants. Humans can get everything they need on a plant-based diet without needless animal suffering. Healthy vegans don’t just remove animal products from an omnivorous diet either; they swap them with kinder alternatives like nuts, beans, seeds, lentils, peas, seitan, tempeh, quinoa, tofu and a host of other foods.</p>`;

const discussion = `<p>At a party many years ago, a boy who looked about 10 was bringing around snacks. I declined the offerings but mentioned I’d be interested in any vegan ones. He then promptly asked me where I get my protein from. I&#39;d heard this many times before, but something about the speed with which he asked this took me aback. When something is so prevalent in culture that it is imprinted in the heads of children, we should wonder how it got there. </p>
<p>It is extremely rare for healthy people with a diverse and adequate caloric diet, vegan or otherwise, to be protein-deficient. Even if you ate nothing but potatoes, so long as you ate enough to maintain your weight, you would come very close to meeting your daily protein requirements. So why are non-vegans obsessed with protein above the myriad other things that people need to be healthy? B12, for instance, is harder to get on plant-based diets, so vegans should supplement their B12. We are rarely asked about B12, however, or anything else well-informed; instead, we are asked about protein. A hint as to where the protein question derives from is the gender of the people who usually ask about it. Men obsess about strength, muscle and masculinity, and associate this with a single nutrient, protein.</p>
<h2>Protein obsession</h2>
<p>The gendered aspects of killing animals have a long history in the human psyche. Most forager societies had gendered tendencies towards labour, with men taking on more of the hunting tasks, especially of larger animals. Given that men focused on this higher-status task, it will come as little surprise that studies show that most diets in the Palaeolithic era were heavily plant-based. The association between masculinity and violent killing, like many of our evolutionary tendencies, has been ripe for exploitation by the marketing industry. There has been a sustained and well-funded marketing effort to tighten the association between masculinity and meat-eating. Typical of this were the high rotation advertisements on 1980s Australian television. The ad&#39;s focus is on a sports jersey-clad young boy, and it starts following him as he runs home. The scene then switches to a father reading a newspaper while seated at a table with the boy and his sister. The mother emerges from the kitchen with the burned, severed leg of some poor animal on a plate. There is no subtlety about the messaging here, or any thought to the diet of the women in the ad; the tagline is &quot;Feed the man meat&quot;. Studies have shown that even female vegetarians view men who abstain from meat as more feminine (though they omit to mention whether the female vegetarians thought that was a good thing). There is inarguably a sexual politics of meat. Masculinity is aligned with killing; the more toxic masculinity, the more it celebrates and reinforces this alignment. Instead of clinging to their toxic masculinity like a security blanket, if many men could free themselves of it, we could all progress a little faster to a better world for humans and animals. Women tend to eat less meat than men, the majority of vegans are women, and women generally hold more pro-social views. It was the gatherers, not the hunters, who had things right all along.</p>
<p>Decent people don&#39;t want to participate in cruelty. To make them do so, the cruelty must be mostly hidden, or they must be convinced that it is necessary. Meat and dairy industry propaganda reaches far more people than unbiased nutritional advice. The industry has long used its financial and political sway to ensure a dominant voice on government nutritional panels and has been repeatedly successful in watering down attempts to make national eating guidelines healthier. They maintain this propaganda war because nutritional science often contradicts perceived national and regional financial self-interest. Not only do we not need to eat animals, but some of the most highly profitable forms of animal products that governments help promote are actively unhealthy. The International Agency for Research on Cancer, a part of the World Health Organisation, has listed processed meats like bacon as a known cancer risk, and red meat generally as a probable cancer risk.</p>
<p>National eating guidelines have been very slow to recognise plant-based sources of protein, such as lentils, one of the first crops ever domesticated, or tofu, which has been part of the Asian diet for at least two thousand years. This long-overdue change in guidelines has happened because they are increasingly being asked to respond to science and human health rather than to economic interests. That this change has correlated with fewer purely patriarchal governments and more women in positions of power generally is unlikely to be purely coincidental. We can not take this improvement for humans and animals for granted, however, as it is under constant assault from the entrenched interests of the animal product industry.</p>
<h2>Science and plant-based diets</h2>
<p>The modern scientific understanding of dietitians about plant-based diets has been slow to filter outwards, even in the wider medical community. I&#39;ve had an elite cardiologist ask me where I get my protein from, and I know many people who have heard such poorly informed things from doctors and medical specialists. Unfortunately, most medical professionals don&#39;t get anything beyond elementary nutritional training and are as susceptible to the unquestioned and outdated ideas cluttering up our culture as everyone else. One study found that doctors in the US and UK got about 11 hours of nutritional training during their long degrees. If we look at the opinions of professionals who have completed an in-depth study of nutrition in their degrees, dietitians, we usually see a very different story. The public stances of peak nutritional bodies around the world generally state similar things to the following position of the Academy of Nutrition and Dietetics:</p>
<p>Appropriately planned vegetarian diets, including total vegetarian or vegan diets, are healthful, nutritionally adequate, and may provide health benefits in the prevention and treatment of certain diseases. Well-planned vegetarian diets are appropriate for individuals during all stages of the life cycle, including pregnancy, lactation, infancy, childhood, and adolescence, and for athletes.</p>
<p>Despite the concern around how much protein vegans are getting, the people who ask about protein rarely know how much we need or how much is actually in different plant foods. There’s no shame in not knowing everything about nutrition; we aren’t born knowing such things, but it would seem reasonable to investigate a little before you criticise a person’s diet or dole out nutritional advice. Many high-profile athletes, including Olympians, weightlifters and bodybuilders, follow a vegan diet. Clearly, these elite athletes are getting what their bodies need for peak performance. Most of them consult nutritional professionals to make sure their diets are meeting their needs. We can all do the same thing as these elite athletes do, to eat healthier diets that are also kinder to animals.</p>
<p>For vegans, there is a serious point here. We should take note of the words “appropriately planned” from the Academy of Nutrition and Dietetics quote above. The idea that vegan diets are always good is just as ill-informed as the idea that they are always bad. Vegan diets aren’t a magic bullet. Like all diets, they can be unhealthy if they contain too much sugar, oil, fat and fried food, and don&#39;t contain enough fruits, vegetables, pulses and whole grains. A vegan diet is different to the one many people grew up eating, so there might be some learning and adjustment needed, particularly if people grew up in a family following a meat-centric diet and haven&#39;t experienced how to cook any other way. Healthy vegans don’t just remove animal products from their diets; they add new things to them. There is a whole world of ingredients we should be more familiar with, particularly the incredible variety of beans and legumes that have been staples of human cultures for so long. Vegans who eat a whole foods, plant-based diet don’t need to worry much about things people who eat too much meat and processed foods struggle with, such as fibre, antioxidants, healthy fats, vitamin C and the other goodies fruits, vegetables and plant protein sources are loaded with. Instead, people on plant-based diets should keep an eye on having adequate sources of things like calcium, vitamin D and omega-3s, and of course, taking a B12 supplement.</p>
<p>In the end, we should be getting our nutritional advice from qualified dietitians, not friends, family, random people, social media or even Vegan Bingo! A great investment in a better life is booking a couple of sessions with a university-qualified nutritionist who understands plant-based diets. They will help you make sure the core of your diet is working towards your long-term health. Healthy food is a gift we can give ourselves and others, that will help maintain physical and mental health, and that will reverberate positively out into the world.<br>As a quote attributed to Hippocrates says, &quot;Let thy food be thy medicine&quot;. Let us follow this advice while also making our food kinder to the world.</p>`;

export {
 heading, short_heading, alternatives, summary, discussion,
};
