
const heading = `What about our canine teeth?`;

const short_heading = `Canine teeth`;

const alternatives = `Meat eating caused human brains to evolve. Our forward-looking eyes mean we are a carnivore`;

const summary = `<p>The fact that we call two of our teeth “canine” is of little more scientific relevance than the fact that we have an Achilles heel or an Adam’s apple. Justifying killing should never be done lightly, and should require an understanding of comparative biology slightly more advanced than we had thousands of years ago when we named these teeth. The argument that our teeth mean we have to eat animals is a clear case of &quot;believe me, not your own eyes&quot;. Look at carnivore teeth, then at herbivore teeth, and then compare both to our own. Humans are opportunistic omnivores. We can largely choose the makeup of our diet, and thus whether it contributes to a more or less compassionate world.</p>`;

const discussion = `<p>Reality usually finds out those who profess things they want to be true, but don&#39;t properly understand. The Ancient Greeks were the ones who gave canine teeth their name. As awe-inspiring as the golden age of Greek philosophy was, it had some fundamental oversights in the way it approached things. The Greek philosopher Aristotle was the father of the biological sciences and one of history&#39;s greatest minds. In parts of Europe, he was so respected that for centuries they simply called him “the philosopher”. Still, he thought women had fewer teeth than men. We know he thought this because he considered it important enough to write it down so other people could learn from his knowledge. If he had taken the time to look in the mouths of more than a couple of women, he would have realised the error of his ways. It seems similar errors in thinking persist in our modern world.</p>
<h2>Canine teeth</h2>
<p>Spend a moment looking at the teeth of various carnivores and herbivores. Human teeth are so obviously similar to herbivore teeth that it is hard to understand anyone bringing this up as an argument for human meat-eating; if anything, it should lead to precisely the opposite conclusion. Still, there is that word canine, which apparently people can’t think very far beyond.</p>
<p>”Canine” is one name given to these teeth, but they are also called eye teeth because of where they sit in our skull, or cuspids by the people who are paid to drill into them. You never hear anyone saying, &quot;What about our cuspids?&quot;. Many animals that eat very different diets have canine teeth. We can include in this list antelopes, deer, camels, horses, boars, seals and walruses. Human canine teeth look rather inoffensive compared to some of our completely herbivorous relatives. Highland gorillas have fierce canines, but aside from the occasional insect, they live on plants. Teeth can be used for many things; they are tools and weapons. Canine teeth, more specifically, are used for dominance displays, fighting, gripping and tearing all kinds of foods. In some herbivorous species, only the males have large canine teeth, not because their diet is different from that of females, but because they use them to fight and show dominance. Indeed, even the dogs after whom canine teeth are named are no longer carnivores. Dogs have lived with omnivorous humans for so long that they have also become omnivorous. Some studies even show that domesticated dogs will live longer and healthier lives if fed a plant-based diet. Unlike our teeth, though, despite living with us for thousands of years, the teeth of domestic dogs clearly show their meat-eating origins. Dogs can still kill relatively large animals using their teeth, something humans would find almost impossible. Can you imagine a human trying to hack away at a bull&#39;s neck with their teeth and getting very far?</p>
<p>Human teeth, being mostly like herbivore teeth, might tell us something about the role of meat in our evolutionary diet. Like our closest evolutionary relatives, we lived primarily on plants. There is incredible variation in the diets of humans who lived in often extreme environments, but anywhere that edible plants were plentiful, the human diet mostly consisted of them. Some of our closest relatives, such as chimpanzees, whose teeth are remarkably similar to human teeth, also eat some meat, but it is an incidental part of their diet. In the most meat-heavy chimpanzee troops, animals might make up 5-10% of their calories, but the percentage for most troops is much less. Our teeth and much of our biology tell us humans, also with some regional variation, were similar.</p>
<p>Our now extinct but even closer, the Neanderthals, had larger canine teeth than modern humans. Neanderthals ate much more meat as a percentage of their diet than we Homo Sapiens did, perhaps up to 80% in some regions. Scientists conjecture that our ability to thrive on a much wider array of foods was one of the things that may have contributed to us outcompeting and then entirely replacing the Neanderthals.</p>
<p>If we are comparing the anatomy of dogs and humans, we can see they also have claws, something that all other land-based carnivores have. Look at the human hand compared to our short, soft nails. Our hands are perfectly designed for doing the sort of things tree-dwelling animals do, like swinging from trees and picking fruit. Until our ancestors figured out how to use tools, their meat-eating would have been confined to scavenging and opportunistically catching smaller animals, just as with our closest genetic relatives like chimpanzees.</p>
<h2>Fire, not murder</h2>
<p>The idea that meat eating was entirely responsible for developing larger brains is predominantly wishful carnism. This is an idea some people want to be true because it would help suppress their ethical qualms about our treatment of animals, but there is no really solid evidence for it. For a start, it involves a bit of circular reasoning. Regularly eating a lot of meat, especially of larger animals, wasn&#39;t really possible until humans had figured out how to make and use tools. They used tools in a uniquely human way, not only to kill prey, but to process their carcasses. Given that our advanced tool use is often given as one of the defining points of homo sapien intelligence, the fact that it was necessary before we ate larger amounts of meat should make us question the underlying logic hypothesis.</p>
<p>Having an additional source of nutrients, especially fat and protein, would be helpful, especially in times of scarcity. During periods of extended drought or other difficult climatic conditions when plant foods might be scarce, eating animals might be the only way to stay alive. That is very different, however, to saying it is necessary. Even today, when we look at communities with poor diets, usually due to extreme poverty, it is common for people to advocate eating more meat as a way to nutritionally improve them. While this might be true as an isolated point, the reason these communities&#39; existing diet is poor is that it lacks calories or variety. In either our evolutionary ancestors or communities in poverty today, a mostly plant-based diet would be a healthier way to provide basic nutritional requirements.</p>
<p>The best science suggests that our harnessing of fire was more consequential, aiding our brain development by unlocking additional food sources and nutrients. The brain is mostly fed on glucose, so this would have especially included plant starches and natural sugars. Human digestive tracts are much longer than true carnivores. Our digestive tracts were even longer before the harnessing of fire and the easier nutrition cooking provided to us. The ability to get nutrients from plants more easily enabled our guts to become smaller, allowing for more physiological resources to be put towards brain development. Looking back on prehistoric times is rarely easy; maybe we’ll have more knowledge in the future, but for now, the hopeful claims of people saying meat &quot;made us human&quot; are unwarranted. Justifying modern humanity’s terrible treatment of animals cannot be laid at the feet of our prehistoric ancestors.</p>
<h2>Tree dwellers</h2>
<p>Forward-facing eyes are a strange one, but it comes up. Like most animals, humans have two separate eyes that enable depth perception. There is a theory that prey species&#39; eyes are wider apart to allow better peripheral vision to see attackers, and that hunter species eyes are closer together for more accurate, close depth perception. So far, so good, and this tracks with general trends in the evolutionary world. Where it gets muddled is in thinking that if you don&#39;t have eyes on the sides of your head, that makes you a carnivore, or vice versa. Again, we return to Aristotle’s oversight: theory without looking at the actual world. Starting with our ape cousins, we could list many species that have forward-facing eyes and are primarily or solely herbivores, or ones that have eyes on the sides of their heads that are carnivores. Depth perception is advantageous for many things, such as swinging through branches, leaping over the landscape, and snatching a lovely fruit before someone else does. Eye placement is clearly not a clear evolutionary sign of any single thing. Humans, like nearly all primates, have forward-facing eyes primarily because they or their ancestors lived among the trees.</p>
<h2>Evolution</h2>
<p>Overall, the science is pretty clear that we have to go a long way back to a time when our ancestors ate herbivorous diets like those of the mountain gorillas. As for human anatomy and our evolutionary diet, we have been omnivores for millennia. Our anatomy is omnivorous, predominantly that of a herbivore, but with adaptations to better enable meat eating. Before our advanced tool usage, we used sporadic techniques such as persistence hunting and cliff driving. More common over the longer term, however, we appear to have opportunistically supplemented our diet with relatively small amounts of meat by scavenging. Humans were eating meat well before they harnessed fire, and therefore had to deal with a higher parasitic load from decomposing meat. Our stomach acids are quite strong and are similar to those of animals who survive almost exclusively on carrion, or what is called &quot;risky meat&quot;, like hyenas and vultures. This makes sense when we look at human anatomy; we simply don&#39;t look like predators. We are unlikely to have been able to have animal products as a large portion of our diet until we started to use weapons, especially projectile weapons, and advanced group hunting techniques. There is clearly an evolutionary reason that qualified dietitians tell us to limit how much meat we eat, and make sure our diet is mostly composed of fruits, vegetables, legumes and whole grains to be healthy.</p>
<p>There is the question of how much we must be limited by what our ancestors ate. The average daily diet includes at least one of the amazing variety of foods that became available to the rest of the world after the colonisation of the Americas began in 1492: corn, potatoes, pumpkins, tomatoes, peppers, peanuts, beans, and, of course, chocolate. Should we avoid such foods because our ancestors had never seen a potato, or just simply enjoy having access to them? Humans living in developed societies have an environment where a vast variety of foods are superabundant. This is fairly unique in human history. It gives us the ability to make choices about what we eat, and this includes ethical choices. Nutritional science tells us we can live healthily on many different diets, including entirely plant-based diets free from animal products. Indeed, most nutritionists and nutritional bodies say that the majority of people would benefit from moving towards a more whole-food, plant-based diet. Using biology to justify our treatment of animals in our food systems is not consistent with modern biological or dietary science. </p>
<p>Once you strip away what people would like to believe out of habit, you are left with a simple truth of profound ethical importance to the world. We have the freedom to use our conscience in deciding what, or whom, we eat. We can make compassionate choices and contribute to a kinder world…if we want it.</p>`;

export {
 heading, short_heading, alternatives, summary, discussion,
};
