
const heading = `What about our canine teeth?`;

const alternatives = `Meat eating caused human brains to evolve. Our forward-looking eyes mean we are a carnivore`;

const short_answer = `<p>The fact that we call two of our teeth “canine” is of little more scientific relevance than the fact that we have an Achilles heel or an Adam’s apple. Justifying killing should never be done lightly, and should require an understanding of comparative biology slightly more advanced than we had thousands of years ago when we named these teeth. The argument that our teeth prove we ate animals is a clear case of &quot;believe me, not your own eyes&quot;. Look at carnivore teeth, then at herbivore teeth, and then compare both to our own. Humans are opportunistic omnivores. We can largely choose the makeup of our diet, and thus whether it contributes to a more or less compassionate world.</p>`;

const long_answer = `<p>Reality eventually finds out those who profess things they would like to be true, but never properly inform themselves about. The Ancient Greeks were the ones who gave canine teeth their name. As awe-inspiring as the golden age of Greek philosophy was, it had some fundamental oversights in the way it approached things. The Greek philosopher Aristotle was the father of the biological sciences and one of history&#39;s greatest minds. In parts of Europe, he was so respected that they simply called him “the philosopher” for centuries. Yet, he wrote in all seriousness that women had fewer teeth than men, and took the time to write it down so other people could learn from his knowledge. If he had taken the time to look in the mouths of more than a couple of women, he would have realised the error of his ways.</p>
<h2>Canine teeth</h2>
<p>Much the same thing can be said about the idea that canine teeth are evidence that we are meat eaters. Spend some time looking at the teeth of a carnivore or a herbivore. Human teeth are so overwhelmingly, obviously similar to herbivore teeth that it is hard to understand anyone bringing this up as an argument for human meat-eating; if anything, it should lead to precisely the opposite conclusion. Still, there is that word canine, which people don’t think very far beyond.</p>
<p>”Canine” is one name given to a couple of our teeth, but they are also called eye teeth because of where they sit in our skull, or cuspids by the people who are paid to drill into them. Many animals that eat very different diets have canine teeth. We can include in this list antelopes, deer, camels, horses, boars, seals and walruses. Human canine teeth look rather inoffensive compared to some of our completely herbivorous relatives. Highland gorillas, for instance, have fierce canine teeth, but other than the occasional insect, they live on plants. Canine teeth are used for dominance displays, fighting, gripping and tearing all kinds of foods. In some herbivorous species, only the males have large canine teeth, not because their diet is different to females&#39;, but because they are used in fighting and dominance displays. Indeed, even the dogs after whom canine teeth are named are not carnivores. Dogs have lived with omnivorous humans for so long that they are now omnivores. Some studies show they will live longer and healthier lives if fed a vegetarian diet. Unlike our teeth, though, despite living with us for thousands of years, the teeth of domestic dogs clearly show their meat-eating origins. Dogs can kill relatively large animals using their teeth, something humans would find almost impossible. Dogs also have claws, something that all other land-based carnivores have, but humans obviously lack, instead having hands perfectly designed for swinging in trees and picking fruit.</p>
<p>Human teeth, being mostly like herbivore teeth, might tell us something about the role of meat in our evolutionary diet. Like our closest evolutionary relatives, we lived primarily on plants. There is incredible variation in the diets of humans who lived in often extreme environments, but anywhere that edible plants were plentiful, the human diet mostly consisted of them. Some of our closest relatives, such as chimpanzees, whose teeth are remarkably similar to human teeth, also eat some meat, but it is an incidental part of their diet. In the most meat-heavy chimpanzee troops, animals might make up 5-10% of their calories, but the percentage for most troops is much less. Our teeth and much of our biology tell us humans, also with some regional variation, were similar.</p>
<h2>Fire, not murder</h2>
<p>As for the idea that meat eating was responsible for developing larger brains, it is an idea some people want to be true because it would suppress any ethical qualms they have about our treatment of animals, but there is not any really solid evidence for it as the primary cause of human intelligence. That is not to say that having an additional source of nutrients, especially fat and protein, was not helpful, especially in difficult times. It is common in many contexts to state that meat will nutritionally improve diets. Where this is true, it is usually because the existing diet is lacking in calories or variety. The best science says that it was our harnessing of fire that was most consequential, aiding our brain development by unlocking additional food sources and nutrients. The brain is mostly fed on glucose, so this would have especially included plant starches and natural sugars. Looking back on prehistoric times is rarely easy; maybe we’ll have more knowledge in the future, but for now, the hopeful claims of people looking to claim meat made us human are unwarranted. Justifying modern humanity’s terrible treatment of animals cannot be laid at the feet of our prehistoric ancestors.</p>
<h2>Tree dwellers</h2>
<p>Forward-facing eyes are a strange one, but it comes up. Like most animals, humans have two separate eyes that enable depth perception. There is a theory that prey species&#39; eyes are wider apart to allow better peripheral vision to see attackers, and that hunter species eyes are closer together for more accurate, close depth perception. So far, so good, and this tracks with general trends in the evolutionary world. Where it gets muddled is in thinking that if you don&#39;t have eyes on the sides of your head, that makes you a carnivore, or vice versa. Again, we return to Aristotle’s oversight: theory without looking at the actual world. Starting with our ape cousins, we could list many species that have forward-facing eyes and are primarily or solely herbivores, or ones that have eyes on the sides of their heads that are carnivores. Depth perception is advantageous for many things, such as swinging through branches, leaping over the landscape, and snatching a lovely fruit before someone else does. Eye placement is clearly not a clear evolutionary sign of any single thing. Humans, like nearly all primates, have forward-facing eyes primarily because they or their ancestors lived among the trees.</p>
<h2>Evolution</h2>
<p>Overall, the science is pretty clear that we have to go a long way back to a time when our ancestors ate diets like those of the mountain gorillas. As for human anatomy and our evolutionary diet, we have been omnivores for millennia. Our anatomy is omnivorous, predominantly that of a herbivore, but with adaptations to better enable meat eating. The evidence from our anatomy is that we first opportunistically supplemented our diet with meat by scavenging. Our stomach acids are incredibly strong and are similar to those of animals who survive almost exclusively on carrion, or what is called &quot;risky meat&quot;, like hyenas and vultures. This makes sense when we look at human anatomy; it is not very suited to killing animals of any size until we started to use weapons, especially projectile weapons, and advanced group hunting techniques. There is clearly an evolutionary reason that qualified dietitians tell us to eat mostly fruits, vegetables and whole grains to be healthy, and the people telling us we should just eat meat are random people on the Internet with very short track records.</p>
<p>Humans living in developed societies have an environment where a wide variety of foods are superabundant. This is fairly unique in human history. It gives us the ability to make ethical choices about what we eat. Nutritional science tells us we can live healthily on many different diets, including entirely plant-based diets free from animal products. Indeed, most nutritionists and nutritional bodies say that the majority of people would benefit from moving towards a more whole-food, plant-based diet. Using biology to justify our treatment of animals in our food systems is not consistent with modern biological or dietary science. </p>
<p>Once you strip away what people would like to believe out of habit, you are left with a simple truth of profound ethical importance to the world. We have the freedom to use our conscience in deciding what, or whom, we eat. We can make compassionate choices and contribute to a kinder world…if we want it.</p>`;

export {
 heading, alternatives, short_answer, long_answer,
};
