
const heading = `What about human suffering?`;

const short_heading = `What about people?`;

const alternatives = `You care more about animals than people. We should worry about humans first.`;

const summary = `<p>To think that one can only care about a single issue is a false dichotomy. Humans are complex beings, and most of us can and do care about more than one thing. Surveys consistently find that people who care about animals are more likely to care about human rights and the environment. The idea that we need to ration our compassion or love is a basic misunderstanding - widening our circle of empathy does not diminish, but strengthens it. People are animals too; human suffering is animal suffering; being vegan extends our compassion to its necessary and logical conclusion.</p>`;

const discussion = `<p>What about human suffering? The premise of this statement is that some beings matter and others don&#39;t; that some suffering is legitimate to care about and some isn&#39;t. Humans are apparently at the top of this hierarchy, so high above all other life in every way that any consideration for other beings is ridiculous, even immoral. Such people appear to be arguing that so long as a human suffers in any way, we should not consider any other suffering, no matter how egregious and widespread. This means we should ignore the suffering of tens of billions of non-humans that huddle in factory farms and slaughterhouses, suffering we could relatively easily eliminate by changing parts of our diet, because this is the suffering of lesser beings. Few statements could outline human supremacy and speciesism more succinctly.</p>
<p>This way of thinking is consistent with animal agriculture. The treatment of animals in our farming system embodies the idea that even trivial human desires, like the preference for some ingredients over others, outweigh almost any rights a non-human being should have. The factory farming system takes everything from the animals within it, including the right to freedom, to life, to health, to family, and to live according to their nature. The usually unstated philosophy of anthropocentrism underlying animal product consumption is at the root of our oppressive relationship with all other life. Vegans want to bring this submerged philosophy into the light, so we can have a discussion about whether the current human treatment of animals is consistent with living ethically. </p>
<p>The call for dualism between humans and other species should be rejected not only on moral grounds, but also increasingly on the basis of scientific evidence. Social science has asked questions about whether people who care deeply about animal suffering consequently care less about other ethical issues, such as human suffering. The studies show that the opposite is true, that the more people care about non-human animals, the more likely they are to care about humans as well. Kindness or its opposite appears to be a general product of our character that applies regardless of which species we interact with. This is backed up by criminal science, where animal abuse is highly correlated, and often predictive, of abusive behaviour towards humans. Misusing one&#39;s power over another sentient being again seems to reflect a person&#39;s character rather than some thought-through hierarchy of species sentience. Biological science has also, since at least Darwin, rejected the idea of humans as a completely separate kind of being. Science has superseded religious notions that we have yet to completely jettison from our culture, such as the Christian idea that humans alone have souls and that other animals were created for our use or dominion. The common evolutionary patterns we share with other animals in our bodies are so obvious that it is hard to believe that we failed to acknowledge them for so long; only a religious story that we needed so deeply to believe could stop us from seeing these common patterns. Modern DNA evidence has only more deeply confirmed that animals are our kin, and some of our very close kin. We share 98.8% of our DNA with chimpanzees, in comparison to the 99.7% we share with Neanderthals, with whom we could interbreed. The call for greater compassion towards non-human animals is based not only on moral intuition and common feeling, but on our ever-deepening scientific understanding of humanity&#39;s place within evolution.</p>
<h2>Focusing on difference</h2>
<p>There is a noticeable human tendency to focus on the difference between non-human animals and us, so much so that we could almost call it a cognitive bias. For many years I worked at a university and would attend lectures given for the public on a wide variety of fields. The number of times eminent academics from different disciplines would start a sentence with &quot;The difference between humans and other animals is&quot; was quite startling. I found it particularly noticeable because usually the words which followed the start of this sentence were some combination of obviously wrong, tenuous, incomplete or unknowable. Regardless of how poor the comparison was, the audience would inevitably nod along, as if it was so pleasant for them to be told they were better than other species, a premise they had already unquestioningly internalised, that some part of their rational brain was being disengaged when hearing a sentence that started with this premise. For centuries, humans were called &quot;The tool users&quot; until it was shown just how many animals use, and sometimes make, tools. The key difference between humans and other animals has shifted to various aspects of thinking, rationality, emotion, culture and so on, which one after the other have been shot down by behavioural biology. Many academics and writers would have saved themselves an intellectual dead end if they had listened to Darwin, who in the nineteenth century pointed out that the difference between humans and other animals was one of degree and not kind. Of course, when you tell people what they want to hear, that they are better and higher than others, you get a very sympathetic hearing. There is no doubt the human mind has unique aspects in the realm of abstraction and information processing, but the inaccuracy of almost all attempts to nail down the difference more specifically than this tells us more about the limitations and self-serving nature of our minds than it reveals about non-human animals. We have an incomplete understanding of our own consciousness and that of other animals; we try to clumsily point to the differences between them and us, but this is not knowledge, but rather a substitute for knowledge.</p>
<h2>Moral consistency</h2>
<p>We would find far more fertile ground in intellectual and ethical progress by focusing on the commonality between ourselves and other beings. Again Darwin was at the scientific forefront here, pointing to how similar our internal worlds were to those of other animals. We know a large part of the experience of other animals because human suffering is animal suffering, human emotions are animal emotions. The species in our factory farms and slaughterhouses experience feelings that we would recognise in ourselves. Other animals are capable of experiencing pleasure, pain, fear, hope, hunger, thirst, anxiety, depression, affection, curiosity, parental bonding, and a full gamut of emotions. To what level their experience is different to ours, even if in some ways their experience might be less complex, does not make them unworthy of our consideration. Like us, they are a sentient consciousness thrown into this shared existence, and primarily seek safety, security and happiness. In reclaiming our relationship with the animal world, we can look back to the origin of the word animal, rooted in the ancient Greek word anima, or soul. The commonality that this word represents should be the centre of our morality and philosophy towards all sentient life. Most of the ethical duties we owe to other humans, we already owe to them by their inclusion within the word animal.</p>
<p>Martin Luther King said, &quot;Injustice anywhere is a threat to justice everywhere.” This is not only an ethical statement, but a pragmatic one: the simplest morality to teach and internalise is one based on consistent logical principles. Often, the first step in enabling wide-scale atrocities is to justify applying different ethical principles to the desired victims. A phrase pertinent and revealing to our current discussion is often used by perpetrators - &quot;dehumanisation&quot;. Dehumanisation is a necessary step in overcoming our natural human empathy, one which can imagine what it would be like for us to be in someone else&#39;s circumstances. The percentage of people who score highly on the dark triad of personality traits, psychopathy, Machiavellianism, and narcissism, is significant and overrepresented in positions of leadership, but they are still a minority in society. To get the rest of society to behave badly requires a story as to why it is actually behaving ethically. Even some of the worst actors seem to need to believe this kind of story, and go into elaborate justifications as to why their behaviours were moral. When those advocating for war crimes are asked why they considered children, the elderly, non-combatants, or those who posed no threat as legitimate targets for violence, they usually try to justify their crimes as moral and necessary acts of self-defense. It is because most people are basically good and fair that these justifications are necessary. Given this, we would expect to see the same process of justification play out in our societal violence towards animals, and of course we do. The main justifications for violence towards animals have been summarised by Melanie Joy as &quot;Normal, natural, necessary and nice&quot;.</p>
<h2>The ideology of oppression</h2>
<p>It has been said that one of the reasons for the change in human belief systems from the hunter-gatherer paradigm, which tended to respect nature and other creatures, and the grazier/farmer paradigm that subjugates other creatures beneath humans, is that the way animals must be treated to farm them can&#39;t be consistent with a level of respect. When you are beating an ox, or are taking a cow&#39;s children away to be slaughtered as you ignore their calls for each other, it wouldn&#39;t be psychologically comfortable for you to think of them as brother and sister beings. To feel better about our oppression of others, we must emphasise that they are less than us, and that our poor treatment of them is somehow morally acceptable. We see this lack of respect in many of the words we use to demean other people, which also demean animals. Whether it be to insult someone&#39;s intelligence, common sense, or their body shape, we often use the names of species that we breed and use: you cow, turkey, goose, chicken, pig, ass, dog, bitch, and so on. This disrespect serves a purpose for us, helping us ignore our empathy in order to feel better about our treatment of thinking, feeling beings.</p>
<p>There have been studies in which people watch films of traditionally farmed animals playing and so on, and the researchers give the study participants a bowl of either animal-based or plant-based snacks to eat while they watch the film. After the film, the researchers ask the study participants to rate the animals on aspects like intelligence and moral worth. Those who watch the films while eating the animal-derived snacks rate the animals lower on all morally relevant measures than those given the plant-derived snacks. It seems that people know that there is significant animal cruelty in our farming systems and so need to justify their participation in this mistreatment by demeaning the sentience of the animals; however, they don&#39;t appear to do this consciously. The intellectual mechanism behind this is called cognitive dissonance, a state where a person has two conflicting beliefs, especially ethical beliefs, that must be reconciled. The carnist ethical conflict is fairly transparent: people know eating animals requires cruelty, while at the same time believing it is morally unacceptable to be cruel to animals. There are two paths towards resolving this dilemma: the first is to change our treatment of animals, and the second is to create an internal narrative that justifies not changing and continuing our cruelty towards animals. Too many people take the second, lazier and more selfish path that requires them to demean the sentience of animals. This is how powerfully our perceived self-interest perverts our thinking, often happening on a semi-conscious or subconscious level. Our brains will actively resist changes necessary to live more ethical lives, and thus, to be a more ethical person can take a sustained effort of conscious will and introspection.</p>
<p>A revealing phrase that one hears when describing a person or group as having been unjustly or violently treated is &quot;They were treated like animals&quot;. This phrase falls very differently on the ear of someone who rejects speciesism, seeming to reflect an underlying violence and injustice in a society that is acceptable if it is targeted towards the appropriate victims. To look into the fearful eyes of a sentient being or to hear their cries, and to decide that you don&#39;t care about them, does not seem a wholly morally different action when directed towards one species or another. The human ability to feel positive and negative emotions, pleasure and pain, safety or fear, is inherited from our animal origins, not a product of our more recent higher consciousness. Speciesism also seems a short step away from deciding that some subclass or group of our own species requires less ethical consideration. Indeed, we don&#39;t have to hypothesise about this, as we can look back at the history of inter-human atrocities and see how many of them involve equating the targeted group of victims with some species of animal. If we were more morally consistent in teaching compassion towards animals, it seems likely to have a positive effect on our compassion towards each other. There is much to be said for fostering moral consistency, as Aristotle said, our morals are like a muscle that gets stronger through regular exercise.</p>
<h2>Holistic healing</h2>
<p>A plant-based diet reverberates positively out into the world in many ways beyond the lives of farmed animals. Livestock’s inconvenient long shadow is involved in almost every environmental problem, from a local to a global scale. The way we farm animals is one of the primary drivers of the destructive Anthropocene, contributing to air pollution, water contamination, land degradation, species extinction, deforestation, invasive species and climate change. The scale of the livestock industry is almost unimaginable, with pasture covering over half the arable land of the earth. Only a few per cent of the remaining mass of land animals are wild creatures, with the vast majority being either humans or their livestock. Two-thirds of the mass of all birds in the world are now farmed chickens. The land on which grain is grown to feed billions of livestock animals can be repurposed to provide for people in the remaining food-poor regions of the world. Most of the communicable diseases that have plagued humanity throughout history have been a result of our contact with animals, including colds and flu, COVID, the black death, smallpox, Ebola, and AIDS. Somewhere between two-thirds and three-quarters of global antibiotic production is fed to healthy livestock, a reality that threatens to undermine one of the great human health breakthroughs. A better world awaits humans, not just non-humans, if we can turn aside from eating and using them for our own purposes.</p>
<p>To look into the eyes of a dog, a cow, or a child is to see something of ourselves looking back at us, wondering about us. Many animals share with us deep parts of the magical spark of consciousness; to justify diminishing or extinguishing that spark because they do not share our identity is an injustice. We are all earthlings, sharing this experience of existence, together. The great power we hold collectively over the lives of the other species of this world means that our moral choices require deep consideration.</p>
<p>Trying to live an ethical life can be difficult in a society that often profits more from us when we live unethically. Ethics asks much of us, requiring us to change habits and learn new ways of thinking that perhaps it would be more convenient for us not to think about. The separation from our conformist selves can also cause friction in our lives among the people who would prefer we validate their unethical conformity by staying in it with them. There is a higher realm of living, though, one that calls to us beyond the small world of human society and selfish desire. It is a life in which our goal is to continually widen our circles of thought and compassion, and help others to do so. Our collective intellectual and moral progression is bound up in the liberation of the oppressed, and we should look first at those of whatever species whose oppression we contribute to. We do not need to choose between being ethical towards humans or animals; indeed, the highest ethics requires us to choose them both. Thinkers throughout the ages have understood this.</p>
<p>Whilst there are slaughterhouses, there will still be battlefields - Tolstoy</p>
<p>Until we stop harming all other living beings, we are still savages - Thomas Edison</p>
<p>We can judge the heart of a man by his treatment of animals - Immanuel Kant</p>
<p>If you have men who will exclude any of god&#39;s creatures from the shelter of compassion and pity, you will have men who will deal likewise with their fellow men - St Francis of Assisi</p>
<p>By killing, man suppresses in himself, unnecessarily, the highest spiritual capacity, that of sympathy and pity towards living creatures like himself - Tolstoy</p>
<p>While we ourselves are the living graves of murdered beasts, how can we expect any ideal conditions on this earth? - George Bernard Shaw</p>
<p>For as long as men massacre animals, they will kill each other - Pythagoras</p>
<p>The greatness of a nation and its moral progress can be judged by the way its animals are treated - Mahatma Gandhi</p>
<p>Until he extends the circle of his compassion to all living things, man will not himself find peace - Albert Schweitzer</p>`;

export {
 heading, short_heading, alternatives, summary, discussion,
};
